# **__________   KAYAK PROJECT   ___________**

**The goal of this project is to identify the possible destinations for holidays using APIs and webscrapping to find the best hotels in the cities where the weather forecast suits our wishes best.**

## **I. Identification of the possible destinations according to the weather forecast**

Here our goal will be to identify the 5 best cities for us according to the weather forecast for the 7 following days among a list of 35 most touristic cities in France. The weather API we will use (OpenWeatherMap) needs to be provided with longitude and latitude of each city in order to give us the weather forecast. So we will start to gather these information with another API called Nominatum.

### **1. List of the 35 most touristic cities in France**

One Week In.com identified the top-35 cities to visit in France. We store them into the variable `list_35_cities`.

In [33]:
list_35_cities=["Mont Saint Michel",
"St Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]

### **2. Coordinates of every cities**

We are going to use the information of the **API Nominatim** to get the coordinates of each of the top-35 best cities in France

**2.0. Modules import**

In [4]:
import requests
import pandas as pd
import time

**2.1. API request test on one city : Paris**

To identify the correct parameters for our API request, we can first try a request on a single city and then test it in a loop for all the cities in our list. Let's take Paris for this first exemple.

_2.1.1. Identification of the parameters for the API request_

In the API documentation, we can read that :
- there are different ways to find information, for instance, we can find the location of a city by giving it's name with the "/search" element, or we can do the opposite with "/reverse". Here we need to use the "/search" option.
- the endpoint for a request is "https://nominatim.openstreetmap.org/search?<params>"
- we don't need and authentification
- the parameters we need are `q` for "query", it means the city, the `format` (here we want a json format) and the `addressedetail` to breakdown the adress into elements.

_2.1.2. Creation of the request_

In [35]:

# ------------------------------------- Identify the base URL --------------------------------------

url_base="https://nominatim.openstreetmap.org/search"


# -------------------------- Headers (required to avoid 403 error) ---------------------------------

headers={
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/118.0"
}


# ----------------------------------------- Parameters ---------------------------------------------

params={
    "q":"paris", # In this "query" parameter we select Paris for the fist test 
    "format":"json",
    "addressdetails":"1", # When set to 1, include a breakdown of the address into elements. 
    "limit":"1" # We want only one element per city
}


# --------------------------------------- GET request ----------------------------------------------

response=requests.get(url=url_base,headers=headers,params=params)

# Status analyse
print("Status code:", response.status_code)


# --------------------------------------- JSON display ---------------------------------------------

if response.status_code == 200:
    data_paris_coord = response.json()
    print(data_paris_coord)
else:
    print("Error:", response.text)


# ------------------------------- Get the coordinates of the city ----------------------------------

city_paris="Paris"
lat_paris=data_paris_coord[0]["lat"]
lon_paris=data_paris_coord[0]["lon"]
print(f"\nCoordinates of {city_paris} : (Lat : {lat_paris}, Lon : {lon_paris})")


#--------------------------------- Load the data into a dataframe ---------------------------------

# Creation of a dictionary that represents the row of the DataFrame
dict_paris_coord={
    "City" : city_paris,
    "Latitude" : lat_paris,
    "Longitude" : lon_paris
}

# Creation of the dataframe
df_paris_coord=pd.DataFrame([dict_paris_coord])
display(df_paris_coord)

Status code: 200
[{'place_id': 88715228, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 7444, 'lat': '48.8588897', 'lon': '2.3200410', 'class': 'boundary', 'type': 'administrative', 'place_rank': 15, 'importance': 0.897098092136026, 'addresstype': 'suburb', 'name': 'Paris', 'display_name': 'Paris, Île-de-France, France métropolitaine, France', 'address': {'suburb': 'Paris', 'city_district': 'Paris', 'city': 'Paris', 'ISO3166-2-lvl6': 'FR-75C', 'state': 'Île-de-France', 'ISO3166-2-lvl4': 'FR-IDF', 'region': 'France métropolitaine', 'country': 'France', 'country_code': 'fr'}, 'boundingbox': ['48.8155755', '48.9021560', '2.2241220', '2.4697602']}]

Coordinates of Paris : (Lat : 48.8588897, Lon : 2.3200410)

    City    Latitude  Longitude
0  Paris  48.8588897  2.3200410

**2.2. API request for all the cities**

In [36]:

# ------------------------------------- Identify the base URL --------------------------------------

url_base="https://nominatim.openstreetmap.org/search"


# -------------------------- Headers (required to avoid 403 error) ---------------------------------

headers={
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/118.0"
}

# ------------------------------- Loop on the cities in the querry ---------------------------------

list_dict_coord_35_cities=[] # List that will be appended with one dictionary per city

for city in list_35_cities:
    params={
        "q":city, # we loop on the cities of our list 
        "format":"json",
        "addressdetails":"1",
        "limit":"1" 
    }
    response=requests.get(url=url_base,headers=headers,params=params)
    time.sleep(1)

    if response.status_code == 200:
        data = response.json()
    else:
        print("Error:", response.text)


    # Creation of one dictionary per city
    dict_coordinates_35_cities={
        "City" : city,
        "Latitude" : data[0]["lat"],
        "Longitude" : data[0]["lon"]
    }

    # Append each dictionary in the list of dictionaries
    list_dict_coord_35_cities.append(dict_coordinates_35_cities)

**2.3. Creation of a dataframe and export of the data**

In [49]:
# Creation of the dataframe with all the cities' information
df_coord_35_cities=pd.DataFrame(list_dict_coord_35_cities)
display(df_coord_35_cities)

# Export of the dataframe as a CSV file
df_coord_35_cities.to_csv("coordinates_35_cities_csv",index=False)

                            City    Latitude    Longitude
0              Mont Saint Michel  48.6359541   -1.5114600
1                        St Malo  49.3146950  -96.9538228
2                         Bayeux  49.2764624   -0.7024738
3                       Le Havre  49.4938975    0.1079732
4                          Rouen  49.4404591    1.0939658
5                          Paris  48.8588897    2.3200410
6                         Amiens  49.8941708    2.2956951
7                          Lille  50.6365654    3.0635282
8                     Strasbourg  48.5846140    7.7507127
9   Chateau du Haut Koenigsbourg  48.2493820    7.3439412
10                        Colmar  48.0777517    7.3579641
11                     Eguisheim  48.0447968    7.3079618
12                      Besancon  47.2380222    6.0243622
13                         Dijon  47.3215806    5.0414701
14                        Annecy  45.8992348    6.1288847
15                      Grenoble  45.1875602    5.7357819
16                          Lyon  45.7578137    4.8320114
17              Gorges du Verdon  43.7496562    6.3285616
18            Bormes les Mimosas  43.1506968    6.3419285
19                        Cassis  43.2140359    5.5396318
20                     Marseille  43.2961743    5.3699525
21               Aix en Provence  43.5298424    5.4474738
22                       Avignon  43.9492493    4.8059012
23                          Uzes  44.0121279    4.4196718
24                         Nimes  43.8374249    4.3600687
25                 Aigues Mortes  43.5661521    4.1915400
26      Saintes Maries de la mer  43.4515922    4.4277202
27                     Collioure  42.5250500    3.0831554
28                   Carcassonne  43.2130358    2.3491069
29                        Ariege  42.9455368    1.4065544
30                      Toulouse  43.6044638    1.4442433
31                     Montauban  44.0175835    1.3549991
32                      Biarritz  43.4832523   -1.5592776
33                       Bayonne  43.4945144   -1.4736657
34                   La Rochelle  46.1597320   -1.1515951

### **3. Weather forecast for every city**

Now that we have the coordinates of each city, we can access the weather forecast **API Openweathermap** to get the weather forecast for the next 7 days and for each of the cities in our list. First we need to register on the website to get our API key.

**3.0. Modules import**

In [38]:
from dotenv import load_dotenv
import os

**3.1. API request test on one city : Paris**

_3.1.1. Identification of the parameters for the API request_

The One Call API 2.5 provides the following weather data for any geographical coordinates (longitude/latitude) that we will provide :

- Current weather
- Minute forecast for 1 hour
- Hourly forecast for 48 hours
- Daily forecast for 7 days
- National weather alerts
- Historical weather data for the previous 5 days
- Current and forecast weat

=> We are interested in the Daily forecast for 7 days so we will select the parameter `daily` by excluding the list `current`,`minutely`,`hourly`,`alerts` in the "exclude" parameter

For the units, we will select the parameter `metric` in order to have the temperature in Celsius and the wind speed in metre/sec (otherwise the default temperature is in Kelvin).

Finally, we will have to use an API key so we will store it in our local environment and use the dotenv library to access it.

_3.1.2. Creation of the request_

In [39]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in /opt/anaconda3/lib/python3.13/site-packages (1.1.0)

In [40]:
#------------------------------- Load variables from .env file -----------------------------------

load_dotenv()

# -------------------------- Access the key securely from the environment -------------------------

API_KEY = os.getenv("API_KEY")

# -------------------------------------------- API call -------------------------------------------

url_base="https://api.openweathermap.org/data/2.5/forecast"

params = {
    "lat":lon_paris,
    "lon": lat_paris,
    "units":"metric",
    "exclude":"current,minutely,hourly,alerts",
    "appid":API_KEY,
}

response = requests.get(url_base,params=params)
print(response.url)

# -------------------------------------- Response analysis ----------------------------------------

if response.status_code == 200:
    json_paris_weather = response.json()
    print(json_paris_weather)
else:
    print("Error:", response.text)

https://api.openweathermap.org/data/2.5/forecast?lat=2.3200410&lon=48.8588897&units=metric&exclude=current%2Cminutely%2Chourly%2Calerts&appid=28089930b22b3f568e2d5c225cd39da2
{'cod': '200', 'message': 0, 'cnt': 40, 'list': [{'dt': 1776092400, 'main': {'temp': 28.73, 'feels_like': 31.02, 'temp_min': 28.73, 'temp_max': 28.73, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.12, 'deg': 84, 'gust': 3.3}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-13 15:00:00'}, {'dt': 1776103200, 'main': {'temp': 28.68, 'feels_like': 31.08, 'temp_min': 28.59, 'temp_max': 28.68, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1012, 'humidity': 64, 'temp_kf': 0.09}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.85, 'deg': 91, 'gust': 4.13}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-13 18:00:00'}, {'dt': 1776114000, 'main': {'temp': 28.5, 'feels_like': 30.76, 'temp_min': 28.39, 'temp_max': 28.5, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 64, 'temp_kf': 0.11}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.55, 'deg': 86, 'gust': 3.8}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-13 21:00:00'}, {'dt': 1776124800, 'main': {'temp': 28.13, 'feels_like': 30.25, 'temp_min': 28.13, 'temp_max': 28.13, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 65, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 72}, 'wind': {'speed': 4.03, 'deg': 91, 'gust': 4.26}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-14 00:00:00'}, {'dt': 1776135600, 'main': {'temp': 28.27, 'feels_like': 30.77, 'temp_min': 28.27, 'temp_max': 28.27, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 67, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 13}, 'wind': {'speed': 5.03, 'deg': 92, 'gust': 5.26}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-14 03:00:00'}, {'dt': 1776146400, 'main': {'temp': 28.43, 'feels_like': 30.92, 'temp_min': 28.43, 'temp_max': 28.43, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1013, 'humidity': 66, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 14}, 'wind': {'speed': 5.22, 'deg': 93, 'gust': 5.52}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-14 06:00:00'}, {'dt': 1776157200, 'main': {'temp': 28.57, 'feels_like': 30.89, 'temp_min': 28.57, 'temp_max': 28.57, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.34, 'deg': 96, 'gust': 4.57}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-14 09:00:00'}, {'dt': 1776168000, 'main': {'temp': 28.7, 'feels_like': 30.97, 'temp_min': 28.7, 'temp_max': 28.7, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 99}, 'wind': {'speed': 3.96, 'deg': 97, 'gust': 4.2}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-14 12:00:00'}, {'dt': 1776178800, 'main': {'temp': 28.71, 'feels_like': 30.99, 'temp_min': 28.71, 'temp_max': 28.71, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 77}, 'wind': {'speed': 3.98, 'deg': 101, 'gust': 4.23}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-14 15:00:00'}, {'dt': 1776189600, 'main': {'temp': 28.63, 'feels_like': 30.99, 'temp_min': 28.63, 'temp_max': 28.63, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1012, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 59}, 'wind': {'speed': 3.99, 'deg': 104, 'gust': 4.24}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-14 18:00:00'}, {'dt': 1776200400, 'main': {'temp': 28.34, 'feels_like': 30.62, 'temp_min': 28.34, 'temp_max': 28.34, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 65, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 58}, 'wind': {'speed': 3.86, 'deg': 104, 'gust': 4.16}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-14 21:00:00'}, {'dt': 1776211200, 'main': {'temp': 28.07, 'feels_like': 30.4, 'temp_min': 28.07, 'temp_max': 28.07, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 67, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 51}, 'wind': {'speed': 3.98, 'deg': 119, 'gust': 4.16}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-15 00:00:00'}, {'dt': 1776222000, 'main': {'temp': 28.05, 'feels_like': 30.5, 'temp_min': 28.05, 'temp_max': 28.05, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 68, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 16}, 'wind': {'speed': 4.15, 'deg': 109, 'gust': 4.4}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-15 03:00:00'}, {'dt': 1776232800, 'main': {'temp': 28.22, 'feels_like': 30.82, 'temp_min': 28.22, 'temp_max': 28.22, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1012, 'humidity': 68, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 19}, 'wind': {'speed': 4.04, 'deg': 109, 'gust': 4.33}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-15 06:00:00'}, {'dt': 1776243600, 'main': {'temp': 28.37, 'feels_like': 31.1, 'temp_min': 28.37, 'temp_max': 28.37, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 68, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 10}, 'wind': {'speed': 3.68, 'deg': 98, 'gust': 3.9}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-15 09:00:00'}, {'dt': 1776254400, 'main': {'temp': 28.49, 'feels_like': 31.33, 'temp_min': 28.49, 'temp_max': 28.49, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1008, 'humidity': 68, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 9}, 'wind': {'speed': 3.01, 'deg': 92, 'gust': 3.26}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-15 12:00:00'}, {'dt': 1776265200, 'main': {'temp': 28.48, 'feels_like': 31.62, 'temp_min': 28.48, 'temp_max': 28.48, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 70, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 51}, 'wind': {'speed': 3.34, 'deg': 92, 'gust': 3.63}, 'visibility': 10000, 'pop': 0.04, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-15 15:00:00'}, {'dt': 1776276000, 'main': {'temp': 28.41, 'feels_like': 31.64, 'temp_min': 28.41, 'temp_max': 28.41, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 69}, 'wind': {'speed': 3.65, 'deg': 104, 'gust': 3.92}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-15 18:00:00'}, {'dt': 1776286800, 'main': {'temp': 28.28, 'feels_like': 31.37, 'temp_min': 28.28, 'temp_max': 28.28, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 55}, 'wind': {'speed': 3.88, 'deg': 124, 'gust': 3.97}, 'visibility': 10000, 'pop': 0.21, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-15 21:00:00'}, {'dt': 1776297600, 'main': {'temp': 27.95, 'feels_like': 30.7, 'temp_min': 27.95, 'temp_max': 27.95, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1008, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 74}, 'wind': {'speed': 3.85, 'deg': 139, 'gust': 3.83}, 'visibility': 10000, 'pop': 0.2, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-16 00:00:00'}, {'dt': 1776308400, 'main': {'temp': 27.91, 'feels_like': 30.49, 'temp_min': 27.91, 'temp_max': 27.91, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 70, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 87}, 'wind': {'speed': 4.19, 'deg': 131, 'gust': 4.23}, 'visibility': 10000, 'pop': 0.03, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-16 03:00:00'}, {'dt': 1776319200, 'main': {'temp': 28.09, 'feels_like': 30.71, 'temp_min': 28.09, 'temp_max': 28.09, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 69, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 73}, 'wind': {'speed': 4.28, 'deg': 124, 'gust': 4.43}, 'visibility': 10000, 'pop': 0.02, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-16 06:00:00'}, {'dt': 1776330000, 'main': {'temp': 28.31, 'feels_like': 30.84, 'temp_min': 28.31, 'temp_max': 28.31, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 67, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 62}, 'wind': {'speed': 2.93, 'deg': 120, 'gust': 3.04}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-16 09:00:00'}, {'dt': 1776340800, 'main': {'temp': 28.39, 'feels_like': 30.85, 'temp_min': 28.39, 'temp_max': 28.39, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1007, 'humidity': 66, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 37}, 'wind': {'speed': 3.28, 'deg': 145, 'gust': 3.28}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-16 12:00:00'}, {'dt': 1776351600, 'main': {'temp': 28.46, 'feels_like': 30.69, 'temp_min': 28.46, 'temp_max': 28.46, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 13}, 'wind': {'speed': 3.36, 'deg': 145, 'gust': 3.41}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-16 15:00:00'}, {'dt': 1776362400, 'main': {'temp': 28.41, 'feels_like': 30.47, 'temp_min': 28.41, 'temp_max': 28.41, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 7}, 'wind': {'speed': 2.81, 'deg': 130, 'gust': 2.92}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-16 18:00:00'}, {'dt': 1776373200, 'main': {'temp': 28.21, 'feels_like': 30.13, 'temp_min': 28.21, 'temp_max': 28.21, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 3.02, 'deg': 131, 'gust': 3.14}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-16 21:00:00'}, {'dt': 1776384000, 'main': {'temp': 28.06, 'feels_like': 29.89, 'temp_min': 28.06, 'temp_max': 28.06, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1008, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 8}, 'wind': {'speed': 3.18, 'deg': 141, 'gust': 3.18}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-17 00:00:00'}, {'dt': 1776394800, 'main': {'temp': 27.96, 'feels_like': 29.61, 'temp_min': 27.96, 'temp_max': 27.96, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 62, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 7}, 'wind': {'speed': 2.8, 'deg': 153, 'gust': 2.73}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-17 03:00:00'}, {'dt': 1776405600, 'main': {'temp': 28.09, 'feels_like': 29.7, 'temp_min': 28.09, 'temp_max': 28.09, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1012, 'humidity': 61, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 38}, 'wind': {'speed': 2.51, 'deg': 146, 'gust': 2.5}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-17 06:00:00'}, {'dt': 1776416400, 'main': {'temp': 28.2, 'feels_like': 29.63, 'temp_min': 28.2, 'temp_max': 28.2, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 59, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 60}, 'wind': {'speed': 1.53, 'deg': 114, 'gust': 1.65}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-17 09:00:00'}, {'dt': 1776427200, 'main': {'temp': 28.46, 'feels_like': 29.9, 'temp_min': 28.46, 'temp_max': 28.46, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1008, 'humidity': 58, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 71}, 'wind': {'speed': 1.6, 'deg': 120, 'gust': 1.67}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-17 12:00:00'}, {'dt': 1776438000, 'main': {'temp': 28.59, 'feels_like': 30.22, 'temp_min': 28.59, 'temp_max': 28.59, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 59, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 24}, 'wind': {'speed': 2.46, 'deg': 103, 'gust': 2.62}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-17 15:00:00'}, {'dt': 1776448800, 'main': {'temp': 28.42, 'feels_like': 30.22, 'temp_min': 28.42, 'temp_max': 28.42, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 61, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 20}, 'wind': {'speed': 2.96, 'deg': 101, 'gust': 3.17}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-17 18:00:00'}, {'dt': 1776459600, 'main': {'temp': 28.26, 'feels_like': 30.22, 'temp_min': 28.26, 'temp_max': 28.26, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 19}, 'wind': {'speed': 2.81, 'deg': 101, 'gust': 3.05}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-17 21:00:00'}, {'dt': 1776470400, 'main': {'temp': 28, 'feels_like': 30.15, 'temp_min': 28, 'temp_max': 28, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 66, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 23}, 'wind': {'speed': 3.37, 'deg': 106, 'gust': 3.59}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-18 00:00:00'}, {'dt': 1776481200, 'main': {'temp': 28.02, 'feels_like': 30.44, 'temp_min': 28.02, 'temp_max': 28.02, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 68, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 6}, 'wind': {'speed': 3.43, 'deg': 110, 'gust': 3.67}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-18 03:00:00'}, {'dt': 1776492000, 'main': {'temp': 28.18, 'feels_like': 30.88, 'temp_min': 28.18, 'temp_max': 28.18, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1012, 'humidity': 69, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 20}, 'wind': {'speed': 3.7, 'deg': 108, 'gust': 3.93}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-18 06:00:00'}, {'dt': 1776502800, 'main': {'temp': 28.4, 'feels_like': 31.62, 'temp_min': 28.4, 'temp_max': 28.4, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 35}, 'wind': {'speed': 3.5, 'deg': 94, 'gust': 3.77}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-18 09:00:00'}, {'dt': 1776513600, 'main': {'temp': 28.45, 'feels_like': 31.88, 'temp_min': 28.45, 'temp_max': 28.45, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1008, 'humidity': 72, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 21}, 'wind': {'speed': 3.26, 'deg': 102, 'gust': 3.49}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-18 12:00:00'}], 'city': {'id': 0, 'name': '', 'coord': {'lat': 2.32, 'lon': 48.8589}, 'country': '', 'population': 0, 'timezone': 10800, 'sunrise': 1776048007, 'sunset': 1776091787}}

In [41]:
#---------------------------------- Analysis of the response and the nested dictionaries --------------------------
import json

json_paris_weather=json_paris_weather['list'] # We keep only the list of dictionaries that we need

print(json.dumps(json_paris_weather, indent=4)) # Formatted format for a better readability

[
    {
        "dt": 1776092400,
        "main": {
            "temp": 28.73,
            "feels_like": 31.02,
            "temp_min": 28.73,
            "temp_max": 28.73,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 63,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 804,
                "main": "Clouds",
                "description": "overcast clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 3.12,
            "deg": 84,
            "gust": 3.3
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-13 15:00:00"
    },
    {
        "dt": 1776103200,
        "main": {
            "temp": 28.68,
            "feels_like": 31.08,
            "temp_min": 28.59,
            "temp_max": 28.68,
            "pressure": 1011,
            "sea_level": 1011,
            "grnd_level": 1012,
            "humidity": 64,
            "temp_kf": 0.09
        },
        "weather": [
            {
                "id": 804,
                "main": "Clouds",
                "description": "overcast clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 3.85,
            "deg": 91,
            "gust": 4.13
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-13 18:00:00"
    },
    {
        "dt": 1776114000,
        "main": {
            "temp": 28.5,
            "feels_like": 30.76,
            "temp_min": 28.39,
            "temp_max": 28.5,
            "pressure": 1011,
            "sea_level": 1011,
            "grnd_level": 1011,
            "humidity": 64,
            "temp_kf": 0.11
        },
        "weather": [
            {
                "id": 804,
                "main": "Clouds",
                "description": "overcast clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 3.55,
            "deg": 86,
            "gust": 3.8
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-13 21:00:00"
    },
    {
        "dt": 1776124800,
        "main": {
            "temp": 28.13,
            "feels_like": 30.25,
            "temp_min": 28.13,
            "temp_max": 28.13,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 65,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 72
        },
        "wind": {
            "speed": 4.03,
            "deg": 91,
            "gust": 4.26
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-14 00:00:00"
    },
    {
        "dt": 1776135600,
        "main": {
            "temp": 28.27,
            "feels_like": 30.77,
            "temp_min": 28.27,
            "temp_max": 28.27,
            "pressure": 1011,
            "sea_level": 1011,
            "grnd_level": 1011,
            "humidity": 67,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 801,
                "main": "Clouds",
                "description": "few clouds",
                "icon": "02d"
            }
        ],
        "clouds": {
            "all": 13
        },
        "wind": {
            "speed": 5.03,
            "deg": 92,
            "gust": 5.26
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-14 03:00:00"
    },
    {
        "dt": 1776146400,
        "main": {
            "temp": 28.43,
            "feels_like": 30.92,
            "temp_min": 28.43,
            "temp_max": 28.43,
            "pressure": 1013,
            "sea_level": 1013,
            "grnd_level": 1013,
            "humidity": 66,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 801,
                "main": "Clouds",
                "description": "few clouds",
                "icon": "02d"
            }
        ],
        "clouds": {
            "all": 14
        },
        "wind": {
            "speed": 5.22,
            "deg": 93,
            "gust": 5.52
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-14 06:00:00"
    },
    {
        "dt": 1776157200,
        "main": {
            "temp": 28.57,
            "feels_like": 30.89,
            "temp_min": 28.57,
            "temp_max": 28.57,
            "pressure": 1011,
            "sea_level": 1011,
            "grnd_level": 1011,
            "humidity": 64,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 804,
                "main": "Clouds",
                "description": "overcast clouds",
                "icon": "04d"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 4.34,
            "deg": 96,
            "gust": 4.57
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-14 09:00:00"
    },
    {
        "dt": 1776168000,
        "main": {
            "temp": 28.7,
            "feels_like": 30.97,
            "temp_min": 28.7,
            "temp_max": 28.7,
            "pressure": 1009,
            "sea_level": 1009,
            "grnd_level": 1009,
            "humidity": 63,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 804,
                "main": "Clouds",
                "description": "overcast clouds",
                "icon": "04d"
            }
        ],
        "clouds": {
            "all": 99
        },
        "wind": {
            "speed": 3.96,
            "deg": 97,
            "gust": 4.2
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-14 12:00:00"
    },
    {
        "dt": 1776178800,
        "main": {
            "temp": 28.71,
            "feels_like": 30.99,
            "temp_min": 28.71,
            "temp_max": 28.71,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 63,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 77
        },
        "wind": {
            "speed": 3.98,
            "deg": 101,
            "gust": 4.23
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-14 15:00:00"
    },
    {
        "dt": 1776189600,
        "main": {
            "temp": 28.63,
            "feels_like": 30.99,
            "temp_min": 28.63,
            "temp_max": 28.63,
            "pressure": 1012,
            "sea_level": 1012,
            "grnd_level": 1012,
            "humidity": 64,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 59
        },
        "wind": {
            "speed": 3.99,
            "deg": 104,
            "gust": 4.24
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-14 18:00:00"
    },
    {
        "dt": 1776200400,
        "main": {
            "temp": 28.34,
            "feels_like": 30.62,
            "temp_min": 28.34,
            "temp_max": 28.34,
            "pressure": 1011,
            "sea_level": 1011,
            "grnd_level": 1011,
            "humidity": 65,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 58
        },
        "wind": {
            "speed": 3.86,
            "deg": 104,
            "gust": 4.16
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-14 21:00:00"
    },
    {
        "dt": 1776211200,
        "main": {
            "temp": 28.07,
            "feels_like": 30.4,
            "temp_min": 28.07,
            "temp_max": 28.07,
            "pressure": 1009,
            "sea_level": 1009,
            "grnd_level": 1009,
            "humidity": 67,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 51
        },
        "wind": {
            "speed": 3.98,
            "deg": 119,
            "gust": 4.16
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-15 00:00:00"
    },
    {
        "dt": 1776222000,
        "main": {
            "temp": 28.05,
            "feels_like": 30.5,
            "temp_min": 28.05,
            "temp_max": 28.05,
            "pressure": 1011,
            "sea_level": 1011,
            "grnd_level": 1011,
            "humidity": 68,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 801,
                "main": "Clouds",
                "description": "few clouds",
                "icon": "02d"
            }
        ],
        "clouds": {
            "all": 16
        },
        "wind": {
            "speed": 4.15,
            "deg": 109,
            "gust": 4.4
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-15 03:00:00"
    },
    {
        "dt": 1776232800,
        "main": {
            "temp": 28.22,
            "feels_like": 30.82,
            "temp_min": 28.22,
            "temp_max": 28.22,
            "pressure": 1012,
            "sea_level": 1012,
            "grnd_level": 1012,
            "humidity": 68,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 801,
                "main": "Clouds",
                "description": "few clouds",
                "icon": "02d"
            }
        ],
        "clouds": {
            "all": 19
        },
        "wind": {
            "speed": 4.04,
            "deg": 109,
            "gust": 4.33
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-15 06:00:00"
    },
    {
        "dt": 1776243600,
        "main": {
            "temp": 28.37,
            "feels_like": 31.1,
            "temp_min": 28.37,
            "temp_max": 28.37,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 68,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 800,
                "main": "Clear",
                "description": "clear sky",
                "icon": "01d"
            }
        ],
        "clouds": {
            "all": 10
        },
        "wind": {
            "speed": 3.68,
            "deg": 98,
            "gust": 3.9
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-15 09:00:00"
    },
    {
        "dt": 1776254400,
        "main": {
            "temp": 28.49,
            "feels_like": 31.33,
            "temp_min": 28.49,
            "temp_max": 28.49,
            "pressure": 1008,
            "sea_level": 1008,
            "grnd_level": 1008,
            "humidity": 68,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 800,
                "main": "Clear",
                "description": "clear sky",
                "icon": "01d"
            }
        ],
        "clouds": {
            "all": 9
        },
        "wind": {
            "speed": 3.01,
            "deg": 92,
            "gust": 3.26
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-15 12:00:00"
    },
    {
        "dt": 1776265200,
        "main": {
            "temp": 28.48,
            "feels_like": 31.62,
            "temp_min": 28.48,
            "temp_max": 28.48,
            "pressure": 1009,
            "sea_level": 1009,
            "grnd_level": 1009,
            "humidity": 70,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 51
        },
        "wind": {
            "speed": 3.34,
            "deg": 92,
            "gust": 3.63
        },
        "visibility": 10000,
        "pop": 0.04,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-15 15:00:00"
    },
    {
        "dt": 1776276000,
        "main": {
            "temp": 28.41,
            "feels_like": 31.64,
            "temp_min": 28.41,
            "temp_max": 28.41,
            "pressure": 1011,
            "sea_level": 1011,
            "grnd_level": 1011,
            "humidity": 71,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 69
        },
        "wind": {
            "speed": 3.65,
            "deg": 104,
            "gust": 3.92
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-15 18:00:00"
    },
    {
        "dt": 1776286800,
        "main": {
            "temp": 28.28,
            "feels_like": 31.37,
            "temp_min": 28.28,
            "temp_max": 28.28,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 71,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 55
        },
        "wind": {
            "speed": 3.88,
            "deg": 124,
            "gust": 3.97
        },
        "visibility": 10000,
        "pop": 0.21,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-15 21:00:00"
    },
    {
        "dt": 1776297600,
        "main": {
            "temp": 27.95,
            "feels_like": 30.7,
            "temp_min": 27.95,
            "temp_max": 27.95,
            "pressure": 1008,
            "sea_level": 1008,
            "grnd_level": 1008,
            "humidity": 71,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 74
        },
        "wind": {
            "speed": 3.85,
            "deg": 139,
            "gust": 3.83
        },
        "visibility": 10000,
        "pop": 0.2,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-16 00:00:00"
    },
    {
        "dt": 1776308400,
        "main": {
            "temp": 27.91,
            "feels_like": 30.49,
            "temp_min": 27.91,
            "temp_max": 27.91,
            "pressure": 1009,
            "sea_level": 1009,
            "grnd_level": 1009,
            "humidity": 70,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 804,
                "main": "Clouds",
                "description": "overcast clouds",
                "icon": "04d"
            }
        ],
        "clouds": {
            "all": 87
        },
        "wind": {
            "speed": 4.19,
            "deg": 131,
            "gust": 4.23
        },
        "visibility": 10000,
        "pop": 0.03,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-16 03:00:00"
    },
    {
        "dt": 1776319200,
        "main": {
            "temp": 28.09,
            "feels_like": 30.71,
            "temp_min": 28.09,
            "temp_max": 28.09,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 69,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04d"
            }
        ],
        "clouds": {
            "all": 73
        },
        "wind": {
            "speed": 4.28,
            "deg": 124,
            "gust": 4.43
        },
        "visibility": 10000,
        "pop": 0.02,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-16 06:00:00"
    },
    {
        "dt": 1776330000,
        "main": {
            "temp": 28.31,
            "feels_like": 30.84,
            "temp_min": 28.31,
            "temp_max": 28.31,
            "pressure": 1009,
            "sea_level": 1009,
            "grnd_level": 1009,
            "humidity": 67,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04d"
            }
        ],
        "clouds": {
            "all": 62
        },
        "wind": {
            "speed": 2.93,
            "deg": 120,
            "gust": 3.04
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-16 09:00:00"
    },
    {
        "dt": 1776340800,
        "main": {
            "temp": 28.39,
            "feels_like": 30.85,
            "temp_min": 28.39,
            "temp_max": 28.39,
            "pressure": 1007,
            "sea_level": 1007,
            "grnd_level": 1007,
            "humidity": 66,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 802,
                "main": "Clouds",
                "description": "scattered clouds",
                "icon": "03d"
            }
        ],
        "clouds": {
            "all": 37
        },
        "wind": {
            "speed": 3.28,
            "deg": 145,
            "gust": 3.28
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-16 12:00:00"
    },
    {
        "dt": 1776351600,
        "main": {

In [42]:
#--------------------------------- Load the data into a dataframe ---------------------------------

# Our Json response contains nested dictionaries so we will use json_normalize to flatten it in order 
# to use it to create a dataframe.

RECORD_PATH = "weather" #record_path`: The key inside each dictionary that points to the LIST of items we 
#want to flatten.


META_FIELDS = [
        'dt',
        ["main","temp"],
        ["main","feels_like"],
        ["main","temp_min"],
        ["main","temp_max"],
        ["main","pressure"],
        ["main","sea_level"],
        ["main","grnd_level"],
        ["main","humidity"],
        ["main","temp_kf"],
        ["clouds","all"],
        ["wind","speed"],
        ["wind","deg"],
        ["wind","gust"],
        "visibility",
        "pop",
        ["sys","pop"],
        "dt_txt"
        ] # `meta`: A list of keys from the *parent* dictionary that 
#we want to keep and repeat for each flattened record.

json_normalized_paris_weather = pd.json_normalize(
data=json_paris_weather,
record_path=RECORD_PATH,
meta=META_FIELDS,
errors='ignore'  # This is important for handling missing/empty lists
)

# Creation of the dataframe
display(json_normalized_paris_weather) # We don't do pd.datatframe() because the normalized json is already a dataframe, we just need to display it

,id,main,description,icon,dt,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,...,main.humidity,main.temp_kf,clouds.all,wind.speed,wind.deg,wind.gust,visibility,pop,sys.pop,dt_txt
0,804,Clouds,overcast clouds,04n,1776092400,28.73,31.02,28.73,28.73,1010,...,63,0,100,3.12,84,3.3,10000,0,NaN,2026-04-13 15:00:00
1,804,Clouds,overcast clouds,04n,1776103200,28.68,31.08,28.59,28.68,1011,...,64,0.09,100,3.85,91,4.13,10000,0,NaN,2026-04-13 18:00:00
2,804,Clouds,overcast clouds,04n,1776114000,28.5,30.76,28.39,28.5,1011,...,64,0.11,100,3.55,86,3.8,10000,0,NaN,2026-04-13 21:00:00
3,803,Clouds,broken clouds,04n,1776124800,28.13,30.25,28.13,28.13,1010,...,65,0,72,4.03,91,4.26,10000,0,NaN,2026-04-14 00:00:00
4,801,Clouds,few clouds,02d,1776135600,28.27,30.77,28.27,28.27,1011,...,67,0,13,5.03,92,5.26,10000,0,NaN,2026-04-14 03:00:00
5,801,Clouds,few clouds,02d,1776146400,28.43,30.92,28.43,28.43,1013,...,66,0,14,5.22,93,5.52,10000,0,NaN,2026-04-14 06:00:00
6,804,Clouds,overcast clouds,04d,1776157200,28.57,30.89,28.57,28.57,1011,...,64,0,100,4.34,96,4.57,10000,0,NaN,2026-04-14 09:00:00
7,804,Clouds,overcast clouds,04d,1776168000,28.7,30.97,28.7,28.7,1009,...,63,0,99,3.96,97,4.2,10000,0,NaN,2026-04-14 12:00:00
8,803,Clouds,broken clouds,04n,1776178800,28.71,30.99,28.71,28.71,1010,...,63,0,77,3.98,101,4.23,10000,0,NaN,2026-04-14 15:00:00
9,803,Clouds,broken clouds,04n,1776189600,28.63,30.99,28.63,28.63,1012,...,64,0,59,3.99,104,4.24,10000,0,NaN,2026-04-14 18:00:00
10,803,Clouds,broken clouds,04n,1776200400,28.34,30.62,28.34,28.34,1011,...,65,0,58,3.86,104,4.16,10000,0,NaN,2026-04-14 21:00:00
11,803,Clouds,broken clouds,04n,1776211200,28.07,30.4,28.07,28.07,1009,...,67,0,51,3.98,119,4.16,10000,0,NaN,2026-04-15 00:00:00
12,801,Clouds,few clouds,02d,1776222000,28.05,30.5,28.05,28.05,1011,...,68,0,16,4.15,109,4.4,10000,0,NaN,2026-04-15 03:00:00
13,801,Clouds,few clouds,02d,1776232800,28.22,30.82,28.22,28.22,1012,...,68,0,19,4.04,109,4.33,10000,0,NaN,2026-04-15 06:00:00
14,800,Clear,clear sky,01d,1776243600,28.37,31.1,28.37,28.37,1010,...,68,0,10,3.68,98,3.9,10000,0,NaN,2026-04-15 09:00:00
15,800,Clear,clear sky,01d,1776254400,28.49,31.33,28.49,28.49,1008,...,68,0,9,3.01,92,3.26,10000,0,NaN,2026-04-15 12:00:00
16,803,Clouds,broken clouds,04n,1776265200,28.48,31.62,28.48,28.48,1009,...,70,0,51,3.34,92,3.63,10000,0.04,NaN,2026-04-15 15:00:00
17,803,Clouds,broken clouds,04n,1776276000,28.41,31.64,28.41,28.41,1011,...,71,0,69,3.65,104,3.92,10000,0,NaN,2026-04-15 18:00:00
18,803,Clouds,broken clouds,04n,1776286800,28.28,31.37,28.28,28.28,1010,...,71,0,55,3.88,124,3.97,10000,0.21,NaN,2026-04-15 21:00:00
19,803,Clouds,broken clouds,04n,1776297600,27.95,30.7,27.95,27.95,1008,...,71,0,74,3.85,139,3.83,10000,0.2,NaN,2026-04-16 00:00:00
20,804,Clouds,overcast clouds,04d,1776308400,27.91,30.49,27.91,27.91,1009,...,70,0,87,4.19,131,4.23,10000,0.03,NaN,2026-04-16 03:00:00
21,803,Clouds,broken clouds,04d,1776319200,28.09,30.71,28.09,28.09,1010,...,69,0,73,4.28,124,4.43,10000,0.02,NaN,2026-04-16 06:00:00
22,803,Clouds,broken clouds,04d,1776330000,28.31,30.84,28.31,28.31,1009,...,67,0,62,2.93,120,3.04,10000,0,NaN,2026-04-16 09:00:00
23,802,Clouds,scattered clouds,03d,1776340800,28.39,30.85,28.39,28.39,1007,...,66,0,37,3.28,145,3.28,10000,0,NaN,2026-04-16 12:00:00
24,801,Clouds,few clouds,02n,1776351600,28.46,30.69,28.46,28.46,1009,...,64,0,13,3.36,145,3.41,10000,0,NaN,2026-04-16 15:00:00
25,800,Clear,clear sky,01n,1776362400,28.41,30.47,28.41,28.41,1010,...,63,0,7,2.81,130,2.92,10000,0,NaN,2026-04-16 18:00:00
26,800,Clear,clear sky,01n,1776373200,28.21,30.13,28.21,28.21,1009,...,63,0,0,3.02,131,3.14,10000,0,NaN,2026-04-16 21:00:00
27,800,Clear,clear sky,01n,1776384000,28.06,29.89,28.06,28.06,1008,...,63,0,8,3.18,141,3.18,10000,0,NaN,2026-04-17 00:00:00
28,800,Clear,clear sky,01d,1776394800,27.96,29.61,27.96,27.96,1010,...,62,0,7,2.8,153,2.73,10000,0,NaN,2026-04-17 03:00:00
29,802,Clouds,scattered clouds,03d,1776405600,28.09,29.7,28.09,28.09,1012,...,61,0,38,2.51,146,2.5,10000,0,NaN,2026-04-17 06:00:00
30,803,Clouds,broken clouds,04d,1776416400,28.2,29.63,28.2,28.2,1010,...,59,0,60,1.53,114,1.65,10000,0,NaN,2026-04-17 09:00:00
31,803,Clouds,broken clouds,04d,1776427200,28.46,29.9,28.46,28.46,1008,...,58,0,71,1.6,120,1.67,10000,0,NaN,2026-04-17 12:00:00
32,801,Clouds,few clouds,02n,1776438000,28.59,30.22,28.59,28.59,1009,...,59,0,24,2.46,103,2.62,10000,0,NaN,2026-04-17 15:00:00
33,801,Clouds,few clouds,02n,1776448800,28.42,30.22,28.42,28.42,1011,...,61,0,20,2.96,101,3.17,10000,0,NaN,2026-04-17 18:00:00
34,801,Clouds,few clouds,02n,1776459600,28.26,30.22,28.26,28.26,1010,...,63,0,19,2.81,101,3.05,10000,0,NaN,2026-04-17 21:00:00
35,801,Clouds,few clouds,02n,1776470400,28,30.15,28,28,1009,...,66,0,23,3.37,106,3.59,10000,0,NaN,2026-04-18 00:00:00
36,800,Clear,clear sky,01d,1776481200,28.02,30.44,28.02,28.02,1010,...,68,0,6,3.43,110,3.67,10000,0,NaN,2026-04-18 03:00:00
37,801,Clouds,few clouds,02d,1776492000,28.18,30.88,28.18,28.18,1012,...,69,0,20,3.7,108,3.93,10000,0,NaN,2026-04-18 06:00:00
38,802,Clouds,scattered clouds,03d,1776502800,28.4,31.62,28.4,28.4,1010,...,71,0,35,3.5,94,3.77,10000,0,NaN,2026-04-18 09:00:00
39,801,Clouds,few clouds,02d,1776513600,28.45,31.88,28.45,28.45,1008,...,72,0,21,3.26,102,3.49,10000,0,NaN,2026-04-18 12:00:00

**List of variable in the json response and the data frame that we wish to keep (checked variables):**

Variables not nested:
- [ ] **`dt`** : Time of data forecasted, unix, UTC
- [x] **`visibility`**: Average visibility (meter) 
- [x] **`pop`**: Probability of precipitation (0 to 1 where 0=0% and 1=100%) 
- [x] **`dt_txt`** #  Time of data forecasted, ISO, UTC 


Variables in **`main`** : 
- [x] **`temp`** : Temperature (°C) 
- [x] **`feels_like`**: Human perception of the temperature (°C) 
- [x] **`temp_min`**: Minimum temperature at the moment of calculation (°C) . This is minimal forecasted temperature (within large megalopolises and urban areas), use this parameter optionally.
- [x] **`temp_max`**: Maximum temperature at the moment of calculation (°C).  This is minimal forecasted temperature (within large megalopolises and urban areas), use this parameter optionally.
- [ ] **`pressure`**: Atmospheric pressure on the sea level (hPa)
- [ ] **`sea_level`**: Atmospheric pressure on the sea level (hPa)
- [ ] **`grnd_level`**: Atmospheric pressure on the ground level (hPa)
- [x] **`humidity`**: Humidity % 
- [ ] **`temp_kf`**: Internal parameter

Variables in **`weather`** : 
- [ ] **`id`**: Weather condition id
- [ ] **`main`**: Group of weather parameters (Rain, Snow, Clouds etc.)
- [x] **`description`**: Weather condition within the group 
- [ ] **`icon`**: Weather icon id
  
Variable in **`cloud`** : 
- [x] **`all`**: Cloudiness, %

Variables in **`wind`**:
- [x] **`speed`**: Wind speed (meter/sec) 
- [ ] **`deg`**: Wind direction (degree)
- [x] **`gust`**: Wind gust (meter/sec) 

Variable in **`sys`** : 
- [x] **`pop`**: Part of the day (n=night, d=day)

In [43]:
#----------------------------------- Selection of columns of interest -------------------------------------

columns_to_keep=['dt_txt','main.temp','main.feels_like','main.temp_min','main.temp_max','main.humidity','description','clouds.all','pop','sys.pop','wind.speed','wind.gust','visibility']
df_weather_paris= json_normalized_paris_weather[columns_to_keep].copy()

display(df_weather_paris)

,dt_txt,main.temp,main.feels_like,main.temp_min,main.temp_max,main.humidity,description,clouds.all,pop,sys.pop,wind.speed,wind.gust,visibility
0,2026-04-13 15:00:00,28.73,31.02,28.73,28.73,63,overcast clouds,100,0,NaN,3.12,3.3,10000
1,2026-04-13 18:00:00,28.68,31.08,28.59,28.68,64,overcast clouds,100,0,NaN,3.85,4.13,10000
2,2026-04-13 21:00:00,28.5,30.76,28.39,28.5,64,overcast clouds,100,0,NaN,3.55,3.8,10000
3,2026-04-14 00:00:00,28.13,30.25,28.13,28.13,65,broken clouds,72,0,NaN,4.03,4.26,10000
4,2026-04-14 03:00:00,28.27,30.77,28.27,28.27,67,few clouds,13,0,NaN,5.03,5.26,10000
5,2026-04-14 06:00:00,28.43,30.92,28.43,28.43,66,few clouds,14,0,NaN,5.22,5.52,10000
6,2026-04-14 09:00:00,28.57,30.89,28.57,28.57,64,overcast clouds,100,0,NaN,4.34,4.57,10000
7,2026-04-14 12:00:00,28.7,30.97,28.7,28.7,63,overcast clouds,99,0,NaN,3.96,4.2,10000
8,2026-04-14 15:00:00,28.71,30.99,28.71,28.71,63,broken clouds,77,0,NaN,3.98,4.23,10000
9,2026-04-14 18:00:00,28.63,30.99,28.63,28.63,64,broken clouds,59,0,NaN,3.99,4.24,10000
10,2026-04-14 21:00:00,28.34,30.62,28.34,28.34,65,broken clouds,58,0,NaN,3.86,4.16,10000
11,2026-04-15 00:00:00,28.07,30.4,28.07,28.07,67,broken clouds,51,0,NaN,3.98,4.16,10000
12,2026-04-15 03:00:00,28.05,30.5,28.05,28.05,68,few clouds,16,0,NaN,4.15,4.4,10000
13,2026-04-15 06:00:00,28.22,30.82,28.22,28.22,68,few clouds,19,0,NaN,4.04,4.33,10000
14,2026-04-15 09:00:00,28.37,31.1,28.37,28.37,68,clear sky,10,0,NaN,3.68,3.9,10000
15,2026-04-15 12:00:00,28.49,31.33,28.49,28.49,68,clear sky,9,0,NaN,3.01,3.26,10000
16,2026-04-15 15:00:00,28.48,31.62,28.48,28.48,70,broken clouds,51,0.04,NaN,3.34,3.63,10000
17,2026-04-15 18:00:00,28.41,31.64,28.41,28.41,71,broken clouds,69,0,NaN,3.65,3.92,10000
18,2026-04-15 21:00:00,28.28,31.37,28.28,28.28,71,broken clouds,55,0.21,NaN,3.88,3.97,10000
19,2026-04-16 00:00:00,27.95,30.7,27.95,27.95,71,broken clouds,74,0.2,NaN,3.85,3.83,10000
20,2026-04-16 03:00:00,27.91,30.49,27.91,27.91,70,overcast clouds,87,0.03,NaN,4.19,4.23,10000
21,2026-04-16 06:00:00,28.09,30.71,28.09,28.09,69,broken clouds,73,0.02,NaN,4.28,4.43,10000
22,2026-04-16 09:00:00,28.31,30.84,28.31,28.31,67,broken clouds,62,0,NaN,2.93,3.04,10000
23,2026-04-16 12:00:00,28.39,30.85,28.39,28.39,66,scattered clouds,37,0,NaN,3.28,3.28,10000
24,2026-04-16 15:00:00,28.46,30.69,28.46,28.46,64,few clouds,13,0,NaN,3.36,3.41,10000
25,2026-04-16 18:00:00,28.41,30.47,28.41,28.41,63,clear sky,7,0,NaN,2.81,2.92,10000
26,2026-04-16 21:00:00,28.21,30.13,28.21,28.21,63,clear sky,0,0,NaN,3.02,3.14,10000
27,2026-04-17 00:00:00,28.06,29.89,28.06,28.06,63,clear sky,8,0,NaN,3.18,3.18,10000
28,2026-04-17 03:00:00,27.96,29.61,27.96,27.96,62,clear sky,7,0,NaN,2.8,2.73,10000
29,2026-04-17 06:00:00,28.09,29.7,28.09,28.09,61,scattered clouds,38,0,NaN,2.51,2.5,10000
30,2026-04-17 09:00:00,28.2,29.63,28.2,28.2,59,broken clouds,60,0,NaN,1.53,1.65,10000
31,2026-04-17 12:00:00,28.46,29.9,28.46,28.46,58,broken clouds,71,0,NaN,1.6,1.67,10000
32,2026-04-17 15:00:00,28.59,30.22,28.59,28.59,59,few clouds,24,0,NaN,2.46,2.62,10000
33,2026-04-17 18:00:00,28.42,30.22,28.42,28.42,61,few clouds,20,0,NaN,2.96,3.17,10000
34,2026-04-17 21:00:00,28.26,30.22,28.26,28.26,63,few clouds,19,0,NaN,2.81,3.05,10000
35,2026-04-18 00:00:00,28,30.15,28,28,66,few clouds,23,0,NaN,3.37,3.59,10000
36,2026-04-18 03:00:00,28.02,30.44,28.02,28.02,68,clear sky,6,0,NaN,3.43,3.67,10000
37,2026-04-18 06:00:00,28.18,30.88,28.18,28.18,69,few clouds,20,0,NaN,3.7,3.93,10000
38,2026-04-18 09:00:00,28.4,31.62,28.4,28.4,71,scattered clouds,35,0,NaN,3.5,3.77,10000
39,2026-04-18 12:00:00,28.45,31.88,28.45,28.45,72,few clouds,21,0,NaN,3.26,3.49,10000

**3.2 Function for API calls and data preparation**

To call the weather API for each city, we are going to create a function that will request the API and save all the relevant information we have previously identified.

In [105]:
def fetch_weather_data(cities_df):
    """Fetch 7-day weather forecast for each city."""
    
    load_dotenv()
    API_KEY = os.getenv("API_KEY")
    
    if not API_KEY:
        raise ValueError("API_KEY not found in .env file")
    
    url_base = "https://api.openweathermap.org/data/2.5/forecast"
    results = {}
    
    for _, row in cities_df.iterrows():
        city = row['City']
        
        params = {
            "lat": row['Latitude'],
            "lon": row['Longitude'],
            "units": "metric",
            "appid": API_KEY
        }
        
        try:
            response = requests.get(url_base, params=params, timeout=10)
            
            if response.status_code != 200:
                results[city] = (pd.DataFrame(), False)
                continue
            
            # Parse and flatten JSON
            forecast_list = response.json()['list']
            df = pd.json_normalize(forecast_list, errors='ignore')
            
            # Extract weather description
            df['description'] = df['weather'].apply(
                lambda x: x[0]['description'] if isinstance(x, list) and len(x) > 0 else None
            )
            
            # Select and rename columns
            cols_to_keep = {
                'main.temp': 'temp',
                'main.temp_min': 'temp_min',
                'main.temp_max': 'temp_max',
                'main.humidity': 'humidity',
                'pop': 'rain_probability',
                'clouds.all': 'cloudiness',
                'wind.speed': 'wind_speed'
            }
            
            existing_cols = [col for col in cols_to_keep.keys() if col in df.columns]
            weather_df = df[['dt_txt', 'description'] + existing_cols].rename(columns=cols_to_keep)
            
            # Convert types
            weather_df['dt_txt'] = pd.to_datetime(weather_df['dt_txt'])
            for col in weather_df.columns:
                if col not in ['dt_txt', 'description']:
                    weather_df[col] = pd.to_numeric(weather_df[col], errors='coerce')        
            results[city] = (weather_df, True)
            
        except Exception as e:
            results[city] = (pd.DataFrame(), False)
    
    return results

**3.3 Weather API call for all cities**

Now we can use the created function to extract the weather information of the weather forecast for our list of 35 cities.

In [106]:
weather_all_cities_dict = fetch_weather_data(df_coord_35_cities)

In [107]:
weather_all_cities_dict

{'Mont Saint Michel': (                dt_txt       description   temp  temp_min  temp_max  humidity  \
  0  2026-04-14 15:00:00   overcast clouds  13.01     13.01     13.01        87
  1  2026-04-14 18:00:00   overcast clouds  13.17     13.17     13.49        88
  2  2026-04-14 21:00:00   overcast clouds  11.72     11.08     11.72        91
  3  2026-04-15 00:00:00   overcast clouds  11.35     11.35     11.35        93
  4  2026-04-15 03:00:00   overcast clouds  11.04     11.04     11.04        95
  5  2026-04-15 06:00:00        light rain  10.92     10.92     10.92        98
  6  2026-04-15 09:00:00        light rain  13.83     13.83     13.83        92
  7  2026-04-15 12:00:00        light rain  17.26     17.26     17.26        67
  8  2026-04-15 15:00:00        light rain  15.82     15.82     15.82        80
  9  2026-04-15 18:00:00        light rain  14.09     14.09     14.09        81
  10 2026-04-15 21:00:00         clear sky   9.84      9.84      9.84        92
  11 2026-04-16 00:00:00     broken clouds   8.48      8.48      8.48        95
  12 2026-04-16 03:00:00     broken clouds   7.93      7.93      7.93        96
  13 2026-04-16 06:00:00     broken clouds   8.25      8.25      8.25        96
  14 2026-04-16 09:00:00   overcast clouds  13.12     13.12     13.12        80
  15 2026-04-16 12:00:00        light rain  15.22     15.22     15.22        69
  16 2026-04-16 15:00:00        light rain  15.32     15.32     15.32        68
  17 2026-04-16 18:00:00        light rain  13.90     13.90     13.90        80
  18 2026-04-16 21:00:00        light rain  10.83     10.83     10.83        89
  19 2026-04-17 00:00:00     broken clouds   8.76      8.76      8.76        93
  20 2026-04-17 03:00:00         clear sky   7.52      7.52      7.52        92
  21 2026-04-17 06:00:00  scattered clouds   7.97      7.97      7.97        90
  22 2026-04-17 09:00:00   overcast clouds  11.55     11.55     11.55        81
  23 2026-04-17 12:00:00     broken clouds  16.33     16.33     16.33        67
  24 2026-04-17 15:00:00   overcast clouds  15.88     15.88     15.88        72
  25 2026-04-17 18:00:00   overcast clouds  15.64     15.64     15.64        74
  26 2026-04-17 21:00:00   overcast clouds  11.96     11.96     11.96        84
  27 2026-04-18 00:00:00   overcast clouds  10.05     10.05     10.05        91
  28 2026-04-18 03:00:00     broken clouds   9.11      9.11      9.11        92
  29 2026-04-18 06:00:00   overcast clouds   9.82      9.82      9.82        92
  30 2026-04-18 09:00:00   overcast clouds  12.81     12.81     12.81        81
  31 2026-04-18 12:00:00   overcast clouds  12.94     12.94     12.94        80
  32 2026-04-18 15:00:00   overcast clouds  12.04     12.04     12.04        78
  33 2026-04-18 18:00:00   overcast clouds  10.56     10.56     10.56        78
  34 2026-04-18 21:00:00   overcast clouds   9.33      9.33      9.33        91
  35 2026-04-19 00:00:00   overcast clouds   8.42      8.42      8.42        89
  36 2026-04-19 03:00:00     broken clouds   6.54      6.54      6.54        92
  37 2026-04-19 06:00:00     broken clouds   6.59      6.59      6.59        92
  38 2026-04-19 09:00:00         clear sky  11.42     11.42     11.42        70
  39 2026-04-19 12:00:00        few clouds  12.06     12.06     12.06        70

      rain_probability  cloudiness  wind_speed
  0               0.00         100        7.15
  1               0.00         100        6.14
  2               0.00         100        5.38
  3               0.00         100        4.96
  4               0.00         100        4.96
  5               0.20         100        4.79
  6               0.20         100        5.81
  7               0.20          84        8.67
  8               0.97          46        8.32
  9               0.78          37        5.83
  10              0.00           5        4.19
  11              0.00          51        3.98
  12              0.00          83        4.00
  13              0.00          78        3.50
  14              0.00         100        4.44
  15              0.20          88        3.26
  16              0.61          94        2.53
  17              0.36          96        3.13
  18              0.20         100        3.50
  19              0.00          81        2.54
  20              0.00          10        2.36
  21              0.00          27        1.96
  22              0.00         100        2.80
  23              0.00          57        2.47
  24              0.00          93        1.09
  25              0.00          97        0.76
  26              0.00         100        2.10
  27              0.00         100        1.70
  28              0.00          82        1.99
  29              0.00          87        1.39
  30              0.00          92        3.55
  31              0.00          96        4.89
  32              0.00         100        6.13
  33              0.00         100        4.74
  34              0.00         100        3.80
  35              0.00          97        4.56
  36              0.00          82        4.06
  37              0.00          75        3.97
  38              0.00           6        5.24
  39              0.00          24        6.49  ,
  True),
 'St Malo': (                dt_txt      description   temp  temp_min  temp_max  humidity  \
  0  2026-04-14 15:00:00    moderate rain   1.58      1.41      1.58        97
  1  2026-04-14 18:00:00  overcast clouds   2.42      2.42      4.09        94
  2  2026-04-14 21:00:00  overcast clouds   4.98      4.98      6.68        83
  3  2026-04-15 00:00:00    broken clouds   7.87      7.87      7.87        75
  4  2026-04-15 03:00:00        clear sky   4.45      4.45      4.45        90
  5  2026-04-15 06:00:00        clear sky   4.06      4.06      4.06        89
  6  2026-04-15 09:00:00        clear sky   3.49      3.49      3.49        90
  7  2026-04-15 12:00:00       few clouds   3.76      3.76      3.76        89
  8  2026-04-15 15:00:00        clear sky  10.00     10.00     10.00        72
  9  2026-04-15 18:00:00       few clouds  16.66     16.66     16.66        51
  10 2026-04-15 21:00:00    broken clouds  20.72     20.72     20.72        36
  11 2026-04-16 00:00:00    broken clouds  17.24     17.24     17.24        44
  12 2026-04-16 03:00:00  overcast clouds  14.10     14.10     14.10        46
  13 2026-04-16 06:00:00  overcast clouds   5.38      5.38      5.38        87
  14 2026-04-16 09:00:00       light snow  -0.10     -0.10     -0.10        77
  15 2026-04-16 12:00:00  overcast clouds  -2.93     -2.93     -2.93        68
  16 2026-04-16 15:00:00  overcast clouds  -2.48     -2.48     -2.48        72
  17 2026-04-16 18:00:00  overcast clouds  -0.03     -0.03     -0.03        66
  18 2026-04-16 21:00:00  overcast clouds   2.07      2.07      2.07        64
  19 2026-04-17 00:00:00  overcast clouds   0.13      0.13      0.13        76
  20 2026-04-17 03:00:00  overcast clouds  -0.90     -0.90     -0.90        80
  21 2026-04-17 06:00:00  overcast clouds  -1.21     -1.21     -1.21        79
  22 2026-04-17 09:00:00       light snow  -1.61     -1.61     -1.61        81
  23 2026-04-17 12:00:00       light snow  -2.25     -2.25     -2.25        86
  24 2026-04-17 15:00:00       light snow  -2.25     -2.25     -2.25        84
  25 2026-04-17 18:00:00       light snow  -1.97     -1.97     -1.97        86
  26 2026-04-17 21:00:00             snow  -3.39     -3.39     -3.39        92
  27 2026-04-18 00:00:00       light snow  -3.71     -3.71     -3.71        88
  28 2026-04-18 03:00:00  overcast clouds  -4.94     -4.94     -4.94        89
  29 2026-04-18 06:00:00       light snow  -5.37     -5.37     -5.37        89
  30 2026-04-18 09:00:00       light snow  -6.44     -6.44     -6.44        88
  31 2026-04-18 12:00:00       light snow  -7.32     -7.32     -7.32        87
  32 2026-04-18 15:00:00  overcast clouds  -6.26     -6.26     -6.26        82
  33 2026-04-18 18:00:00       light snow  -3.62     -3.62     -3.62        82
  34 2026-04-18 21:00:00       light snow  -1.20     -1.20     -1.20        78
  35 2026-04-19 00:00:00       light snow  -1.99     -1.99     -1.99        76
  36 2026-04-19 03:00:00  overcast clouds  -3.96     -3.96     -3.96        83
  37 2026-04-19 06:00:00    broken clouds  -5.17     -5.17     -5.17        85
  38 2026-04-19 09:00:00        clear sky  -6.69     -6.69     -6.69        87
  39 2026-04-19 12:00:00        clear sky  -6.96     -6.96     -6.96        89

      rain_probability  cloudiness  wind_speed
  0               1.00         100        2.08
  1               0.80         100        0.43
  2               0.00          98        2.27
  3               0.00          71        0.95
  4               0.00           0        3.12
  5               0.00           0        3.43
  6               0.00           0        4.21
  7               0.00          16        6.01
  8               0.00           9        7.36
  9               0.00          17        8.14
  10              0.00          52        6.77
  11              0.00          76        3.66
  12              0.00         100        1.47
  13              0.00         100        7.76
  14              0.92         100        7.72
  15              0.25         100        7.65
  16              0.00         100        6.80
  17              0.00         100        7.47
  18              0.00         100        7.59
  19              0.00         100        7.24
  20              0.00         100        6.49
  21              0.00         100        7.23
  22              0.20         100        7.50
  23              0.23         100        7.34
  24              0.30         100        6.14
  25              0.97         100        6.26
  26              1.00         100        7.10
  27              1.00         100        7.04
  28              0.00         100        7.49
  29              0.20         100        8.51
  30              0.20         100        7.43
  31              0.20         100        9.10
  32              0.00         100        9.02
  33              0.20         100       10.44
  34              0.32         100       10.53
  35              0.20         100       10.19
  36              0.00          87        8.56
  37              0.00          68        6.47
  38              0.00           8        5.41
  39              0.00           9        4.12  ,
  True),
 'Bayeux': (                dt_txt       description   temp  temp_min  temp_max  humidity  \
  0  2026-04-14 15:00:00   overcast clouds  16.14     14.33     16.14        73
  1  2026-04-14 18:00:00   overcast clouds  15.33     13.71     15.33        76
  2  2026-04-14 21:00:00   overcast clouds  12.25     10.30     12.25        87
  3  2026-04-15 00:00:00   overcast clouds   9.57      9.57      9.57        94
  4  2026-04-15 03:00:00   overcast clouds   9.69      9.69      9.69        90
  5  2026-04-15 06:00:00   overcast clouds  10.42     10.42     10.42        92
  6  2026-04-15 09:00:00   overcast clouds  12.83     12.83     12.83        91
  7  2026-04-15 12:00:00        light rain  16.73     16.73     16.73        72
  8  2026-04-15 15:00:00        light rain  16.53     16.53     16.53        80
  9  2026-04-15 18:00:00        light rain  13.21     13.21     13.21        87
  10 2026-04-15 21:00:00         clear sky   8.96      8.96      8.96        93
  11 2026-04-16 00:00:00  scattered clouds   8.46      8.46      8.46        94
  12 2026-04-16 03:00:00   overcast clouds   7.27      7.27      7.27        96
  13 2026-04-16 06:00:00   overcast clouds   7.58      7.58      7.58        96
  14 2026-04-16 09:00:00     broken clouds  12.88     12.88     12.88        79
  15 2026-04-16 12:00:00        light rain  15.46     15.46     15.46        63
  16 2026-04-16 15:00:00     broken clouds  15.41     15.41     15.41        61
  17 2026-04-16 18:00:00   overcast clouds  12.87     12.87     12.87        78
  18 2026-04-16 21:00:00   overcast clouds   9.26      9.26      9.26        89
  19 2026-04-17 00:00:00   overcast clouds   9.89      9.89      9.89        87
  20 2026-04-17 03:00:00        few clouds   7.87      7.87      7.87        94
  21 2026-04-17 06:00:00  scattered clouds   7.69      7.69      7.69        92
  22 2026-04-17 09:00:00     broken clouds  13.66     13.66     13.66        70
  23 2026-04-17 12:00:00     broken clouds  16.17     16.17     16.17        64
  24 2026-04-17 15:00:00     broken clouds  15.35     15.35     15.35        69
  25 2026-04-17 18:00:00        light rain  14.09     14.09     14.09        81
  26 2026-04-17 21:00:00   overcast clouds  10.84     10.84     10.84        86
  27 2026-04-18 00:00:00   overcast clouds   9.74      9.74      9.74        89
  28 2026-04-18 03:00:00     broken clouds   8.44      8.44      8.44        93
  29 2026-04-18 06:00:00     broken clouds   9.14      9.14      9.14        91
  30 2026-04-18 09:00:00   overcast clouds  12.66     12.66     12.66        82
  31 2026-04-18 12:00:00        light rain  11.60     11.60     11.60        88
  32 2026-04-18 15:00:00   overcast clouds  11.24     11.24     11.24        82
  33 2026-04-18 18:00:00   overcast clouds  10.67     10.67     10.67        75
  34 2026-04-18 21:00:00   overcast clouds   7.60      7.60      7.60        92
  35 2026-04-19 00:00:00   overcast clouds   8.27      8.27      8.27        93
  36 2026-04-19 03:00:00  scattered clouds   7.85      7.85      7.85        92
  37 2026-04-19 06:00:00        few clouds   7.76      7.76      7.76        87
  38 2026-04-19 09:00:00         clear sky  10.79     10.79     10.79        69
  39 2026-04-19 12:00:00         clear sky  11.67     11.67     11.67        66

      rain_probability  cloudiness  wind_speed
  0                0.0         100        6.44
  1                0.0         100        5.68
  2                0.0          99        5.08
  3                0.0         100        4.77
  4                0.0         100        5.16
  5                0.0         100        5.46
  6                0.0         100        5.75
  7                0.2         100        7.45
  8                1.0          28        7.56
  9                1.0          16        5.36
  10               0.0           5        2.74
  11               0.0          40        3.75
  12               0.0         100        4.22
  13               0.0         100        4.30
  14               0.0          67        5.16
  15               0.2          60        5.16
  16               0.0          83        4.33
  17               0.0          92        1.09
  18               0.0         100        3.11
  19               0.0          97        3.21
  20               0.0          12        3.85
  21               0.0          32        3.44
  22               0.0          53        3.39
  23               0.0          67        2.83
  24               0.0          75        1.66
  25               0.2          87        1.72
  26               0.0         100        2.16
  27               0.0          99        1.90
  28               0.0          77        2.60
  29               0.0          75        2.44
  30               0.0          88        3.21
  31               0.2          94        3.60
  32               0.0         100        4.04
  33               0.0         100        3.83
  34               0.0         100        3.29
  35               0.0         100        4.05
  36               0.0          39        4.11
  37               0.0          24        3.90
  38               0.0           5        5.91
  39               0.0           4        5.87  ,
  True),
 'Le Havre': (                dt_txt       description   temp  temp_min  temp_max  humidity  \
  0  2026-04-14 15:00:00         clear sky  17.51     12.44     17.51        48
  1  2026-04-14 18:00:00  scattered clouds  15.92     12.75     15.92        59
  2  2026-04-14 21:00:00     broken clouds  13.72     11.83     13.72        68
  3  2026-04-15 00:00:00   overcast clouds  11.54     11.54     11.54        80
  4  2026-04-15 03:00:00   overcast clouds  10.78     10.78     10.78        88
  5  2026-04-15 06:00:00        light rain  10.97     10.97     10.97        90
  6  2026-04-15 09:00:00   overcast clouds  12.18     12.18     12.18        89
  7  2026-04-15 12:00:00        light rain  13.02     13.02     13.02        89
  8  2026-04-15 15:00:00        light rain  14.36     14.36     14.36        83
  9  2026-04-15 18:00:00        light rain  12.71     12.71     12.71        91
  10 2026-04-15 21:00:00        light rain  11.50     11.50     11.50        93
  11 2026-04-16 00:00:00  scattered clouds  10.67     10.67     10.67        92
  12 2026-04-16 03:00:00   overcast clouds   9.80      9.80      9.80        90
  13 2026-04-16 06:00:00   overcast clouds   9.29      9.29      9.29        91
  14 2026-04-16 09:00:00     broken clouds  11.29     11.29     11.29        85
  15 2026-04-16 12:00:00        light rain  12.76     12.76     12.76        77
  16 2026-04-16 15:00:00   overcast clouds  12.94     12.94     12.94        74
  17 2026-04-16 18:00:00   overcast clouds  12.53     12.53     12.53        76
  18 2026-04-16 21:00:00   overcast clouds  12.63     12.63     12.63        71
  19 2026-04-17 00:00:00   overcast clouds  11.02     11.02     11.02        82
  20 2026-04-17 03:00:00        few clouds  10.34     10.34     10.34        89
  21 2026-04-17 06:00:00  scattered clouds   9.89      9.89      9.89        88
  22 2026-04-17 09:00:00     broken clouds  11.55     11.55     11.55        80
  23 2026-04-17 12:00:00  scattered clouds  13.10     13.10     13.10        69
  24 2026-04-17 15:00:00     broken clouds  13.16     13.16     13.16        72
  25 2026-04-17 18:00:00     broken clouds  13.13     13.13     13.13        75
  26 2026-04-17 21:00:00   overcast clouds  13.22     13.22     13.22        75
  27 2026-04-18 00:00:00   overcast clouds  12.15     12.15     12.15        80
  28 2026-04-18 03:00:00   overcast clouds  11.53     11.53     11.53        84
  29 2026-04-18 06:00:00   overcast clouds  11.08     11.08     11.08        89
  30 2026-04-18 09:00:00   overcast clouds  12.42     12.42     12.42        81
  31 2026-04-18 12:00:00   overcast clouds  11.86     11.86     11.86        90
  32 2026-04-18 15:00:00   overcast clouds  11.61     11.61     11.61        84
  33 2026-04-18 18:00:00   overcast clouds  10.88     10.88     10.88        79
  34 2026-04-18 21:00:00   overcast clouds  10.63     10.63     10.63        85
  35 2026-04-19 00:00:00   overcast clouds  10.59     10.59     10.59        84
  36 2026-04-19 03:00:00     broken clouds  10.03     10.03     10.03        85
  37 2026-04-19 06:00:00     broken clouds   9.66      9.66      9.66        79
  38 2026-04-19 09:00:00  scattered clouds  10.34     10.34     10.34        72
  39 2026-04-19 12:00:00  scattered clouds  10.40     10.40     10.40        72

      rain_probability  cloudiness  wind_speed
  0               0.00           0        6.15
  1               0.00          29        4.61
  2               0.00          67        5.51
  3               0.00         100        5.23
  4               0.00         100        5.97
  5               0.20         100        6.02
  6               0.00         100        6.81
  7               0.20         100        6.30
  8               1.00          60        5.82
  9               1.00          43        4.49
  10              0.30          12        3.13
  11              0.00          25        4.00
  12              0.00         100        5.45
  13              0.00          99        5.80
  14              0.00          83        5.19
  15              0.20          81        3.09
  16              0.02          97        2.64
  17              0.00          99        1.06
  18              0.00         100        2.01
  19              0.00         100        3.04
  20              0.00          15        3.09

**3.3 Weather preferences**

For most people, a comfortable weather for holidays is : 
- hot but not too hot (around 25°C), 
- with low humidity, wind and clouds. 
- low rain probability

We are going to create a scoring functions with these parameters to determine the weather score of a given city. Then will be able to compare cities and select the best ones.

In [108]:
 
def score_city_weather(weather_df, ideal_temp=25):
    """Score a city's weather based on 7-day forecast."""
    
    # Aggregate by day
    daily = weather_df.groupby(weather_df['dt_txt'].dt.date).agg({
        'temp': 'mean',
        'temp_min': 'min',
        'temp_max': 'max',
        'humidity': 'mean',
        'rain_probability': 'mean'
    })
    
    # Calculate component scores [0, 1]
    temp_score = (1 - abs(daily['temp'] - ideal_temp) / 10).clip(0, 1)
    humidity_score = 1 - (daily['humidity'] / 100)
    rain_score = 1 - daily['rain_probability']
    stability_score = (1 - (daily['temp_max'] - daily['temp_min']) / 10).clip(0, 1)
    
    # Weighted final score
    daily_score = (
        0.4 * temp_score +
        0.2 * humidity_score +
        0.3 * rain_score +
        0.1 * stability_score
    )
    
    # City score: mean minus std (penalize variability)
    city_score = daily_score.mean() - daily_score.std()
    
    return {
        'avg_temp': daily['temp'].mean(),
        'avg_humidity': daily['humidity'].mean(),
        'rain_prob': daily['rain_probability'].mean() * 100,
        'temp_stability': daily['temp'].std(),
        'score': city_score
    }
 
 
def calculate_weather_scores(weather_results):
    """Calculate scores for all cities."""
    
    scores = []
    
    for city, (weather_df, success) in weather_results.items():
        if not success or weather_df.empty:
            continue
        
        stats = score_city_weather(weather_df)
        scores.append({
            'City': city,
            'Weather_Score': round(stats['score'], 3),
            'Avg_Temp': round(stats['avg_temp'], 1),
            'Avg_Humidity': round(stats['avg_humidity'], 1),
            'Rain_Probability': round(stats['rain_prob'], 1),
            'Temp_Stability': round(stats['temp_stability'], 2)
        })
    
    df = pd.DataFrame(scores).sort_values('Weather_Score', ascending=False).reset_index(drop=True)
    return df

**3.4. Weather scoring for all cities**

In [ ]:
weather_score_all_df = calculate_weather_scores(weather_all_cities_dict)
weather_score_all_df

,City,Weather_Score,Avg_Temp,Avg_Humidity,Rain_Probability,Temp_Stability,Success
0,Collioure,0.453,16.6,56.0,0.0,2.17,True
1,Saintes Maries de la mer,0.412,15.0,64.3,0.0,2.36,True
2,Aix en Provence,0.403,16.0,56.3,0.0,3.25,True
3,Aigues Mortes,0.401,15.4,60.9,0.0,2.26,True
4,Marseille,0.395,15.9,63.3,1.1,2.69,True
5,Nimes,0.394,15.0,59.1,0.0,3.15,True
6,Avignon,0.392,14.7,63.3,0.0,3.32,True
7,Cassis,0.390,15.3,63.6,1.4,2.12,True
8,Uzes,0.381,13.8,64.0,0.0,2.84,True
9,Strasbourg,0.362,12.2,74.4,3.0,1.90,True
10,Carcassonne,0.350,13.9,71.2,2.6,2.40,True
11,Bormes les Mimosas,0.340,15.3,66.4,7.6,1.10,True
12,Le Havre,0.340,11.4,78.8,8.0,0.56,True
13,La Rochelle,0.331,12.6,79.5,4.5,1.52,True
14,Colmar,0.327,12.2,75.0,8.8,1.93,True
15,Biarritz,0.315,13.3,78.5,7.4,1.35,True
16,Bayonne,0.315,13.4,78.9,6.8,1.31,True
17,Eguisheim,0.312,12.0,75.2,11.0,1.92,True
18,Chateau du Haut Koenigsbourg,0.308,9.5,75.4,11.5,2.02,True
19,Dijon,0.292,10.8,81.1,10.0,2.33,True
20,Mont Saint Michel,0.287,11.3,81.4,11.5,1.19,True
21,Bayeux,0.277,10.7,81.6,13.5,0.84,True
22,Lille,0.275,12.3,67.0,12.7,1.23,True
23,Paris,0.274,14.3,56.4,14.8,2.04,True
24,Gorges du Verdon,0.270,11.9,66.5,10.5,1.17,True
25,Amiens,0.264,11.5,74.3,12.7,1.10,True
26,Toulouse,0.259,13.4,72.2,11.1,2.50,True
27,Montauban,0.259,13.2,74.9,11.1,1.97,True
28,Lyon,0.258,11.9,77.2,12.2,2.52,True
29,Rouen,0.242,11.5,77.5,20.2,0.88,True
30,Grenoble,0.230,11.9,85.6,13.5,3.09,True
31,Annecy,0.208,10.4,83.3,18.8,2.22,True
32,Besancon,0.197,10.6,82.3,19.7,2.23,True
33,Ariege,0.197,8.4,75.9,19.4,3.13,True
34,St Malo,0.170,2.8,78.4,24.5,4.78,True

**3.5. Export of the data**

In [63]:
weather_score_all_df.to_csv("weather_best_destinations_csv",index=True)

Top five destinations according to our weather scoring :

In [74]:
top_five_destinations_df = weather_score_all_df.head(5).copy()
top_five_cities_names = weather_score_all_df.head(5)["City"].tolist()

In [78]:
print("The best cities according to the actual weather forecast are :\n")
for name, i in zip(top_five_cities_names,range(1,6)) : 
    print(f"  - N°{i} : {name}")

The best cities according to the actual weather forecast are :

  - N°1 : Collioure
  - N°2 : Saintes Maries de la mer
  - N°3 : Aix en Provence
  - N°4 : Aigues Mortes
  - N°5 : Marseille

In [ ]:
top_five_destinations_df.to_csv("DATA/bookingHotels/top_five_destinations_csv.csv", index=True)

## **II. Identification of the 20 best hotels in the top-5 destinations**

Now that we have defined our top-5 list of destinations, let's check the 20 bests hotels per city using webscrapping techniques on the Booking.com website

### **1. Create a webscrapping function**

As Booking.com actively blocks scraping, we are using Selenium here to gather information for each hotel with : 
- its name,
- the url to its booking.com page,
- Its coordinates: latitude and longitude,
- Its score according to the website users,
- A text description of the hotel.

In [13]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
from datetime import datetime, timedelta, date

In [9]:
def scrape_hotels(city, check_in, check_out, num_hotels=20):
    """Scrape hotels for one city from Booking.com."""
    
    options = Options()
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
    options.add_argument("--no-sandbox")
    
    driver = webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=options
    )
    
    hotels = []
    
    try:
        url = f"https://www.booking.com/searchresults.fr.html?ss={city}&checkin={check_in}&checkout={check_out}&nrpersons=2"
        driver.get(url)
        
        # Wait and scroll
        time.sleep(3)
        driver.execute_script("window.scrollBy(0, window.innerHeight);")
        time.sleep(2)
        
        # Extract hotels
        hotel_elements = driver.find_elements(By.CSS_SELECTOR, "div[data-testid='property-card']")
        
        for elem in hotel_elements[:num_hotels]:
            try:
                # Name
                name = elem.find_element(By.CSS_SELECTOR, "div[data-testid='title']").text
                
                # URL
                link = elem.find_element(By.CSS_SELECTOR, "a[href*='hotel']")
                url_hotel = link.get_attribute("href")
                if not url_hotel.startswith("http"):
                    url_hotel = "https://www.booking.com" + url_hotel
                
                # Rating
                rating = None
                try:
                    import re
                    rating_text = elem.text
                    match = re.search(r'(\d+[.,]\d)', rating_text)
                    if match:
                        rating = float(match.group(1).replace(',', '.'))
                except:
                    pass
                
                hotels.append({
                    'name': name,
                    'url': url_hotel,
                    'rating': rating,
                    'city': city
                })
            except:
                continue
    
    except Exception as e:
        print(f"Error scraping {city}: {str(e)}")
    
    finally:
        driver.quit()
    
    return hotels

### **2. Get hotels information**

In [16]:
def scrape_all_hotels(cities, check_in=None, check_out=None, num_hotels=20):
    """Scrape hotels for all cities."""
    
    if check_in is None:
        check_in = date.today()
        
    if check_out is None:
        check_out = check_in + timedelta(days=7)

    print(check_in, check_out)
    all_hotels = []
    
    for city in cities:
        hotels = scrape_hotels(city, check_in, check_out, num_hotels)
        all_hotels.extend(hotels)
    
    if not all_hotels:
        print("No hotels scraped!")
        return pd.DataFrame()
    
    df = pd.DataFrame(all_hotels)
    df = df.sort_values(['city', 'rating'], ascending=[True, False]).reset_index(drop=True)
    
    return df

In [11]:
cities = pd.read_csv("DATA/bookingHotels/top_five_destinations_csv.csv")

In [17]:
hotels_df = scrape_all_hotels(cities)

2026-04-24 2026-05-01

In [43]:
hotels_df.head()

,name,url,rating,city
0,Casa Gin Tazones,https://www.booking.com/hotel/es/casa-gin-tazo...,9.8,Avg_Humidity
1,Casa Tirador,https://www.booking.com/hotel/es/casa-tirador....,9.8,Avg_Humidity
2,El Rincón de Silvia,https://www.booking.com/hotel/es/el-rincon-de-...,9.7,Avg_Humidity
3,Nordés Apartamentos Turísticos - Bañugues,https://www.booking.com/hotel/es/nordes-aparta...,9.5,Avg_Humidity
4,Hotel El Pescador,https://www.booking.com/hotel/es/el-pescador-t...,9.4,Avg_Humidity

In [18]:
# Save to CSV
hotels_df.to_csv("Data/bookingHotels/all_cities_hotels.csv", index=False)

### **3. Visualizations**

**3.1. Top destinations map**

In [38]:
import plotly.express as px

def plot_top_destinations(df):
    """Interactive map with modern Mapbox-style background."""

    top5 = df.head(5)

    fig = px.scatter_mapbox(
        top5,
        lat="Latitude",
        lon="Longitude",
        text="City",
        zoom=4.5,
        center={"lat": 46.6, "lon": 2.5},  # France
        height=600
    )

    fig.update_traces(
        marker=dict(size=10, color="red"),
        hovertemplate="<b>%{text}</b><extra></extra>"
    )

    fig.update_layout(
        mapbox_style="carto-positron",  
        margin={"r":0,"t":40,"l":0,"b":0},
        title="<b>Top 5 Best Destinations in France</b>"
    )

    return fig

In [26]:
coordinates_35_cities = pd.read_csv("DATA/BookingHotels/coordinates_35_cities_csv.csv")

In [30]:
selected_cities = [
    "Collioure",
    "Saintes Maries de la mer",
    "Aix en Provence",
    "Aigues Mortes",
    "Marseille"
]

# filtrer les 5 villes
top_cities_coordinates = coordinates_35_cities[coordinates_35_cities["City"].isin(selected_cities)]

In [31]:
top_cities_coordinates

                        City   Latitude  Longitude
20                 Marseille  43.296174   5.369953
21           Aix en Provence  43.529842   5.447474
25             Aigues Mortes  43.566152   4.191540
26  Saintes Maries de la mer  43.451592   4.427720
27                 Collioure  42.525050   3.083155

In [39]:
plot_top_destinations(top_cities_coordinates)

**3.2. Top hotels map**

In [40]:
def plot_top_hotels(hotels_df):
    """Plot top-20 hotels on interactive map."""
    
    # Remove hotels without coordinates
    hotels_with_coords = hotels_df.dropna(subset=['latitude', 'longitude'])
    
    if len(hotels_with_coords) == 0:
        print("No hotels with coordinates found")
        return None
    
    top20 = hotels_with_coords.nlargest(20, 'rating')
    
    # Color by city
    colors = {'Paris': '#1f77b4', 'Barcelona': '#ff7f0e', 'Miami': '#2ca02c', 
              'Rome': '#d62728', 'Amsterdam': '#9467bd'}
    
    fig = go.Figure()
    
    for city in top20['city'].unique():
        city_hotels = top20[top20['city'] == city]
        
        fig.add_trace(go.Scattergeo(
            lon=city_hotels['longitude'],
            lat=city_hotels['latitude'],
            mode='markers',
            marker=dict(
                size=city_hotels['rating'] * 3,
                color=colors.get(city, '#7f7f7f'),
                opacity=0.8,
                line=dict(width=2, color='white')
            ),
            hovertext=('<b>' + city_hotels['name'] + '</b><br>' +
                      'Rating: ' + city_hotels['rating'].astype(str) + '/10'),
            hoverinfo='text',
            name=city
        ))
    
    fig.update_layout(
        title='<b>Top-20 Hotels by Rating</b>',
        geo=dict(
            projection_type='natural earth',
            showland=True,
            landcolor='rgb(243, 243, 243)',
            showocean=True,
            oceancolor='rgb(204, 229, 255)'
        ),
        height=600
    )
    
    return fig

In [42]:
hotels_df.head()

,name,url,rating,city
0,Casa Gin Tazones,https://www.booking.com/hotel/es/casa-gin-tazo...,9.8,Avg_Humidity
1,Casa Tirador,https://www.booking.com/hotel/es/casa-tirador....,9.8,Avg_Humidity
2,El Rincón de Silvia,https://www.booking.com/hotel/es/el-rincon-de-...,9.7,Avg_Humidity
3,Nordés Apartamentos Turísticos - Bañugues,https://www.booking.com/hotel/es/nordes-aparta...,9.5,Avg_Humidity
4,Hotel El Pescador,https://www.booking.com/hotel/es/el-pescador-t...,9.4,Avg_Humidity

### **4. Save elements to S3** ###

In [ ]:
 
def upload_to_s3(dataframe, filename, bucket_name="kayak_project_bucket"):
    """Upload DataFrame as CSV to S3."""
    
    try:
        # Create S3 client
        s3 = boto3.client('s3')
        
        # Convert to CSV in memory
        csv_buffer = dataframe.to_csv(index=False).encode('utf-8')
        
        # Upload
        s3.put_object(Bucket=bucket_name, Key=filename, Body=csv_buffer)
        logger.info(f"✓ Uploaded {filename} to s3://{bucket_name}/")
        
    except Exception as e:
        logger.error(f"Failed to upload {filename}: {str(e)}")
 
 
def save_figure_to_s3(figure, filename, bucket_name="kayak_project_bucket"):
    """Save Plotly figure as HTML to S3."""
    
    try:
        s3 = boto3.client('s3')
        
        # Save to HTML string
        html_string = figure.to_html()
        
        # Upload
        s3.put_object(
            Bucket=bucket_name,
            Key=filename,
            Body=html_string.encode('utf-8'),
            ContentType='text/html'
        )
        logger.info(f"✓ Uploaded {filename} to s3://{bucket_name}/")
        
    except Exception as e:
        logger.error(f"Failed to upload {filename}: {str(e)}")