# **__________   KAYAK PROJECT   ___________**

**The goal of this project is to identify the possible destinations for holidays using APIs and webscrapping to find the best hotels in the cities where the weather forecast suits our wishes best.**

## **I. Identification of the possible destinations according to the weather forecast**

Here our goal will be to identify the 5 best cities for us according to the weather forecast for the 7 following days among a list of 35 most touristic cities in France. The weather API we will use (OpenWeatherMap) needs to be provided with longitude and latitude of each city in order to give us the weather forecast. So we will start to gather these information with another API called Nominatum.

### **1. List of the 35 most touristic cities in France**

One Week In.com identified the top-35 cities to visit in France. We store them into the variable `list_35_cities`.

In [7]:
list_35_cities=["Mont Saint Michel",
"St Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]

### **2. Coordinates of every cities**

We are going to use the information of the **API Nominatim** to get the coordinates of each of the top-35 best cities in France

**2.0. Modules import**

In [8]:
import requests
import pandas as pd
import time
import os

**2.1. API request test on one city : Paris**

To identify the correct parameters for our API request, we can first try a request on a single city and then test it in a loop for all the cities in our list. Let's take Paris for this first exemple.

_2.1.1. Identification of the parameters for the API request_

In the API documentation, we can read that :
- there are different ways to find information, for instance, we can find the location of a city by giving it's name with the "/search" element, or we can do the opposite with "/reverse". Here we need to use the "/search" option.
- the endpoint for a request is "https://nominatim.openstreetmap.org/search?<params>"
- we don't need and authentification
- the parameters we need are `q` for "query", it means the city, the `format` (here we want a json format) and the `addressedetail` to breakdown the adress into elements.

_2.1.2. Creation of the request_

In [9]:

# ------------------------------------- Identify the base URL --------------------------------------

url_base="https://nominatim.openstreetmap.org/search"


# -------------------------- Headers (required to avoid 403 error) ---------------------------------

headers={
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/118.0"
}


# ----------------------------------------- Parameters ---------------------------------------------

params={
    "q":"paris", # In this "query" parameter we select Paris for the fist test 
    "format":"json",
    "addressdetails":"1", # When set to 1, include a breakdown of the address into elements. 
    "limit":"1" # We want only one element per city
}


# --------------------------------------- GET request ----------------------------------------------

response=requests.get(url=url_base,headers=headers,params=params)

# Status analyse
print("Status code:", response.status_code)


# --------------------------------------- JSON display ---------------------------------------------

if response.status_code == 200:
    data_paris_coord = response.json()
    print(data_paris_coord)
else:
    print("Error:", response.text)


# ------------------------------- Get the coordinates of the city ----------------------------------

city_paris="Paris"
lat_paris=data_paris_coord[0]["lat"]
lon_paris=data_paris_coord[0]["lon"]
print(f"\nCoordinates of {city_paris} : (Lat : {lat_paris}, Lon : {lon_paris})")


#--------------------------------- Load the data into a dataframe ---------------------------------

# Creation of a dictionary that represents the row of the DataFrame
dict_paris_coord={
    "City" : city_paris,
    "Latitude" : lat_paris,
    "Longitude" : lon_paris
}

# Creation of the dataframe
df_paris_coord=pd.DataFrame([dict_paris_coord])
display(df_paris_coord)

Status code: 200
[{'place_id': 89081766, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 7444, 'lat': '48.8588897', 'lon': '2.3200410', 'class': 'boundary', 'type': 'administrative', 'place_rank': 15, 'importance': 0.897098092136026, 'addresstype': 'suburb', 'name': 'Paris', 'display_name': 'Paris, Île-de-France, France métropolitaine, France', 'address': {'suburb': 'Paris', 'city_district': 'Paris', 'city': 'Paris', 'ISO3166-2-lvl6': 'FR-75C', 'state': 'Île-de-France', 'ISO3166-2-lvl4': 'FR-IDF', 'region': 'France métropolitaine', 'country': 'France', 'country_code': 'fr'}, 'boundingbox': ['48.8155755', '48.9021560', '2.2241220', '2.4697602']}]

Coordinates of Paris : (Lat : 48.8588897, Lon : 2.3200410)

    City    Latitude  Longitude
0  Paris  48.8588897  2.3200410

**2.2. API request for all the cities**

In [10]:

# ------------------------------------- Identify the base URL --------------------------------------

url_base="https://nominatim.openstreetmap.org/search"


# -------------------------- Headers (required to avoid 403 error) ---------------------------------

headers={
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/118.0"
}

# ------------------------------- Loop on the cities in the querry ---------------------------------

list_dict_coord_35_cities=[] # List that will be appended with one dictionary per city

for city in list_35_cities:
    params={
        "q":city, # we loop on the cities of our list 
        "format":"json",
        "addressdetails":"1",
        "limit":"1" 
    }
    response=requests.get(url=url_base,headers=headers,params=params)
    time.sleep(1)

    if response.status_code == 200:
        data = response.json()
    else:
        print("Error:", response.text)


    # Creation of one dictionary per city
    dict_coordinates_35_cities={
        "City" : city,
        "Latitude" : data[0]["lat"],
        "Longitude" : data[0]["lon"]
    }

    # Append each dictionary in the list of dictionaries
    list_dict_coord_35_cities.append(dict_coordinates_35_cities)

**2.3. Creation of a dataframe and export of the data**

In [11]:
# Creation of the dataframe with all the cities' information
df_coord_35_cities=pd.DataFrame(list_dict_coord_35_cities)
display(df_coord_35_cities)

# Export of the dataframe as a CSV file
os.makedirs("DATA/bookinghotels", exist_ok=True)
df_coord_35_cities.to_csv("DATA/bookinghotels/coordinates_35_cities_csv.csv", index=False)

                            City    Latitude    Longitude
0              Mont Saint Michel  48.6359541   -1.5114600
1                        St Malo  49.3146950  -96.9538228
2                         Bayeux  49.2764624   -0.7024738
3                       Le Havre  49.4938975    0.1079732
4                          Rouen  49.4404591    1.0939658
5                          Paris  48.8588897    2.3200410
6                         Amiens  49.8941708    2.2956951
7                          Lille  50.6365654    3.0635282
8                     Strasbourg  48.5846140    7.7507127
9   Chateau du Haut Koenigsbourg  48.2493820    7.3439412
10                        Colmar  48.0777517    7.3579641
11                     Eguisheim  48.0447968    7.3079618
12                      Besancon  47.2380222    6.0243622
13                         Dijon  47.3215806    5.0414701
14                        Annecy  45.8992348    6.1288847
15                      Grenoble  45.1875602    5.7357819
16                          Lyon  45.7578137    4.8320114
17              Gorges du Verdon  43.7496562    6.3285616
18            Bormes les Mimosas  43.1506968    6.3419285
19                        Cassis  43.2140359    5.5396318
20                     Marseille  43.2961743    5.3699525
21               Aix en Provence  43.5298424    5.4474738
22                       Avignon  43.9492493    4.8059012
23                          Uzes  44.0121279    4.4196718
24                         Nimes  43.8374249    4.3600687
25                 Aigues Mortes  43.5661521    4.1915400
26      Saintes Maries de la mer  43.4515922    4.4277202
27                     Collioure  42.5250500    3.0831554
28                   Carcassonne  43.2130358    2.3491069
29                        Ariege  42.9455368    1.4065544
30                      Toulouse  43.6044638    1.4442433
31                     Montauban  44.0175835    1.3549991
32                      Biarritz  43.4711438   -1.5527266
33                       Bayonne  43.4945144   -1.4736657
34                   La Rochelle  46.1597320   -1.1515951

### **3. Weather forecast for every city**

Now that we have the coordinates of each city, we can access the weather forecast **API Openweathermap** to get the weather forecast for the next 7 days and for each of the cities in our list. First we need to register on the website to get our API key.

**3.0. Modules import**

In [12]:
from dotenv import load_dotenv

**3.1. API request test on one city : Paris**

_3.1.1. Identification of the parameters for the API request_

The One Call API 2.5 provides the following weather data for any geographical coordinates (longitude/latitude) that we will provide :

- Current weather
- Minute forecast for 1 hour
- Hourly forecast for 48 hours
- Daily forecast for 7 days
- National weather alerts
- Historical weather data for the previous 5 days
- Current and forecast weat

=> We are interested in the Daily forecast for 7 days so we will select the parameter `daily` by excluding the list `current`,`minutely`,`hourly`,`alerts` in the "exclude" parameter

For the units, we will select the parameter `metric` in order to have the temperature in Celsius and the wind speed in metre/sec (otherwise the default temperature is in Kelvin).

Finally, we will have to use an API key so we will store it in our local environment and use the dotenv library to access it.

_3.1.2. Creation of the request_

In [13]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in /opt/anaconda3/lib/python3.13/site-packages (1.1.0)

In [14]:
#------------------------------- Load variables from .env file -----------------------------------

load_dotenv()

# -------------------------- Access the key securely from the environment -------------------------

API_KEY = os.getenv("API_KEY")

# -------------------------------------------- API call -------------------------------------------

url_base="https://api.openweathermap.org/data/2.5/forecast"

params = {
    "lat":lon_paris,
    "lon": lat_paris,
    "units":"metric",
    "exclude":"current,minutely,hourly,alerts",
    "appid":API_KEY,
}

response = requests.get(url_base,params=params)
print(response.url)

# -------------------------------------- Response analysis ----------------------------------------

if response.status_code == 200:
    json_paris_weather = response.json()
    print(json_paris_weather)
else:
    print("Error:", response.text)

https://api.openweathermap.org/data/2.5/forecast?lat=2.3200410&lon=48.8588897&units=metric&exclude=current%2Cminutely%2Chourly%2Calerts&appid=28089930b22b3f568e2d5c225cd39da2
{'cod': '200', 'message': 0, 'cnt': 40, 'list': [{'dt': 1777129200, 'main': {'temp': 29, 'feels_like': 32.73, 'temp_min': 28.7, 'temp_max': 29, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1009, 'humidity': 70, 'temp_kf': 0.3}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 87}, 'wind': {'speed': 3.15, 'deg': 29, 'gust': 3.37}, 'visibility': 10000, 'pop': 0.57, 'rain': {'3h': 0.93}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-25 15:00:00'}, {'dt': 1777140000, 'main': {'temp': 28.98, 'feels_like': 32.87, 'temp_min': 28.9, 'temp_max': 28.98, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1011, 'humidity': 71, 'temp_kf': 0.08}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 94}, 'wind': {'speed': 2.72, 'deg': 49, 'gust': 2.98}, 'visibility': 10000, 'pop': 0.54, 'rain': {'3h': 0.23}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-25 18:00:00'}, {'dt': 1777150800, 'main': {'temp': 28.54, 'feels_like': 32.41, 'temp_min': 28.54, 'temp_max': 28.54, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 74, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.3, 'deg': 39, 'gust': 2.61}, 'visibility': 10000, 'pop': 0.63, 'rain': {'3h': 0.93}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-25 21:00:00'}, {'dt': 1777161600, 'main': {'temp': 28.51, 'feels_like': 32.18, 'temp_min': 28.51, 'temp_max': 28.51, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1008, 'humidity': 73, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.67, 'deg': 17, 'gust': 2.99}, 'visibility': 10000, 'pop': 0.7, 'rain': {'3h': 1.07}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-26 00:00:00'}, {'dt': 1777172400, 'main': {'temp': 28.62, 'feels_like': 32.08, 'temp_min': 28.62, 'temp_max': 28.62, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.68, 'deg': 11, 'gust': 2.59}, 'visibility': 10000, 'pop': 0.75, 'rain': {'3h': 0.19}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-26 03:00:00'}, {'dt': 1777183200, 'main': {'temp': 28.54, 'feels_like': 31.91, 'temp_min': 28.54, 'temp_max': 28.54, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1012, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.3, 'deg': 359, 'gust': 1.23}, 'visibility': 10000, 'pop': 0.72, 'rain': {'3h': 0.18}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-26 06:00:00'}, {'dt': 1777194000, 'main': {'temp': 28.33, 'feels_like': 31.62, 'temp_min': 28.33, 'temp_max': 28.33, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 72, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.02, 'deg': 320, 'gust': 1.08}, 'visibility': 10000, 'pop': 0.6, 'rain': {'3h': 0.92}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-26 09:00:00'}, {'dt': 1777204800, 'main': {'temp': 28.21, 'feels_like': 31.52, 'temp_min': 28.21, 'temp_max': 28.21, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 73, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.22, 'deg': 324, 'gust': 2.54}, 'visibility': 10000, 'pop': 0.74, 'rain': {'3h': 2.86}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-26 12:00:00'}, {'dt': 1777215600, 'main': {'temp': 28.6, 'feels_like': 31.87, 'temp_min': 28.6, 'temp_max': 28.6, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 70, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.42, 'deg': 344, 'gust': 2.56}, 'visibility': 10000, 'pop': 0.72, 'rain': {'3h': 1.31}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-26 15:00:00'}, {'dt': 1777226400, 'main': {'temp': 28.7, 'feels_like': 32.08, 'temp_min': 28.7, 'temp_max': 28.7, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 70, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.71, 'deg': 49, 'gust': 2.01}, 'visibility': 10000, 'pop': 0.61, 'rain': {'3h': 0.12}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-26 18:00:00'}, {'dt': 1777237200, 'main': {'temp': 28.43, 'feels_like': 31.52, 'temp_min': 28.43, 'temp_max': 28.43, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 70, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 75}, 'wind': {'speed': 0.62, 'deg': 144, 'gust': 0.76}, 'visibility': 10000, 'pop': 0.01, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-26 21:00:00'}, {'dt': 1777248000, 'main': {'temp': 28.28, 'feels_like': 31.37, 'temp_min': 28.28, 'temp_max': 28.28, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 50}, 'wind': {'speed': 0.8, 'deg': 235, 'gust': 0.71}, 'visibility': 10000, 'pop': 0.09, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-27 00:00:00'}, {'dt': 1777258800, 'main': {'temp': 28.32, 'feels_like': 31.6, 'temp_min': 28.32, 'temp_max': 28.32, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 72, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 81}, 'wind': {'speed': 1.96, 'deg': 258, 'gust': 1.79}, 'visibility': 10000, 'pop': 0.42, 'rain': {'3h': 0.11}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-27 03:00:00'}, {'dt': 1777269600, 'main': {'temp': 28.33, 'feels_like': 31.78, 'temp_min': 28.33, 'temp_max': 28.33, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1012, 'humidity': 73, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 89}, 'wind': {'speed': 2.09, 'deg': 258, 'gust': 1.95}, 'visibility': 10000, 'pop': 0.49, 'rain': {'3h': 0.16}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-27 06:00:00'}, {'dt': 1777280400, 'main': {'temp': 28.54, 'feels_like': 32.24, 'temp_min': 28.54, 'temp_max': 28.54, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 73, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.73, 'deg': 266, 'gust': 3.5}, 'visibility': 10000, 'pop': 0.49, 'rain': {'3h': 0.39}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-27 09:00:00'}, {'dt': 1777291200, 'main': {'temp': 28.09, 'feels_like': 31.56, 'temp_min': 28.09, 'temp_max': 28.09, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1008, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 501, 'main': 'Rain', 'description': 'moderate rain', 'icon': '10d'}], 'clouds': {'all': 98}, 'wind': {'speed': 2.67, 'deg': 283, 'gust': 2.8}, 'visibility': 10000, 'pop': 0.8, 'rain': {'3h': 3.59}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-27 12:00:00'}, {'dt': 1777302000, 'main': {'temp': 28.54, 'feels_like': 31.91, 'temp_min': 28.54, 'temp_max': 28.54, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 83}, 'wind': {'speed': 1.62, 'deg': 292, 'gust': 1.64}, 'visibility': 10000, 'pop': 0.46, 'rain': {'3h': 0.3}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-27 15:00:00'}, {'dt': 1777312800, 'main': {'temp': 28.48, 'feels_like': 31.78, 'temp_min': 28.48, 'temp_max': 28.48, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 77}, 'wind': {'speed': 0.15, 'deg': 337, 'gust': 0.29}, 'visibility': 10000, 'pop': 0.3, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-27 18:00:00'}, {'dt': 1777323600, 'main': {'temp': 28.31, 'feels_like': 31.58, 'temp_min': 28.31, 'temp_max': 28.31, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 72, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 94}, 'wind': {'speed': 0.56, 'deg': 207, 'gust': 0.44}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-27 21:00:00'}, {'dt': 1777334400, 'main': {'temp': 28.17, 'feels_like': 31.29, 'temp_min': 28.17, 'temp_max': 28.17, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1008, 'humidity': 72, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 93}, 'wind': {'speed': 0.71, 'deg': 194, 'gust': 0.67}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-28 00:00:00'}, {'dt': 1777345200, 'main': {'temp': 28.25, 'feels_like': 31.61, 'temp_min': 28.25, 'temp_max': 28.25, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 73, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 83}, 'wind': {'speed': 1.87, 'deg': 166, 'gust': 1.83}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-28 03:00:00'}, {'dt': 1777356000, 'main': {'temp': 28.44, 'feels_like': 32.02, 'temp_min': 28.44, 'temp_max': 28.44, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 73, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 90}, 'wind': {'speed': 2.28, 'deg': 199, 'gust': 2.16}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-28 06:00:00'}, {'dt': 1777366800, 'main': {'temp': 28.55, 'feels_like': 32.26, 'temp_min': 28.55, 'temp_max': 28.55, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 73, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.27, 'deg': 232, 'gust': 2.23}, 'visibility': 10000, 'pop': 0.24, 'rain': {'3h': 0.16}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-28 09:00:00'}, {'dt': 1777377600, 'main': {'temp': 28.78, 'feels_like': 32.61, 'temp_min': 28.78, 'temp_max': 28.78, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1008, 'humidity': 72, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.67, 'deg': 246, 'gust': 2.52}, 'visibility': 10000, 'pop': 0.33, 'rain': {'3h': 0.61}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-28 12:00:00'}, {'dt': 1777388400, 'main': {'temp': 28.9, 'feels_like': 32.88, 'temp_min': 28.9, 'temp_max': 28.9, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 72, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 92}, 'wind': {'speed': 2.4, 'deg': 226, 'gust': 2.26}, 'visibility': 10000, 'pop': 0.09, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-28 15:00:00'}, {'dt': 1777399200, 'main': {'temp': 28.81, 'feels_like': 32.86, 'temp_min': 28.81, 'temp_max': 28.81, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 73, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 90}, 'wind': {'speed': 2.83, 'deg': 196, 'gust': 2.76}, 'visibility': 10000, 'pop': 0.05, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-28 18:00:00'}, {'dt': 1777410000, 'main': {'temp': 28.61, 'feels_like': 32.57, 'temp_min': 28.61, 'temp_max': 28.61, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 74, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.98, 'deg': 209, 'gust': 2.82}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-28 21:00:00'}, {'dt': 1777420800, 'main': {'temp': 28.51, 'feels_like': 32.52, 'temp_min': 28.51, 'temp_max': 28.51, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1008, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.15, 'deg': 224, 'gust': 3.04}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-29 00:00:00'}, {'dt': 1777431600, 'main': {'temp': 28.57, 'feels_like': 32.66, 'temp_min': 28.57, 'temp_max': 28.57, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.6, 'deg': 209, 'gust': 3.49}, 'visibility': 10000, 'pop': 0.12, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-29 03:00:00'}, {'dt': 1777442400, 'main': {'temp': 28.76, 'feels_like': 33.11, 'temp_min': 28.76, 'temp_max': 28.76, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.3, 'deg': 219, 'gust': 4.17}, 'visibility': 10000, 'pop': 0.12, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-29 06:00:00'}, {'dt': 1777453200, 'main': {'temp': 29, 'feels_like': 33.49, 'temp_min': 29, 'temp_max': 29, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 74, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.25, 'deg': 230, 'gust': 4.3}, 'visibility': 10000, 'pop': 0.05, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-29 09:00:00'}, {'dt': 1777464000, 'main': {'temp': 29.01, 'feels_like': 33.52, 'temp_min': 29.01, 'temp_max': 29.01, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 74, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 96}, 'wind': {'speed': 3.88, 'deg': 237, 'gust': 3.85}, 'visibility': 10000, 'pop': 0.19, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-29 12:00:00'}, {'dt': 1777474800, 'main': {'temp': 29.03, 'feels_like': 33.37, 'temp_min': 29.03, 'temp_max': 29.03, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1010, 'humidity': 73, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 92}, 'wind': {'speed': 3.46, 'deg': 221, 'gust': 3.39}, 'visibility': 10000, 'pop': 0.08, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-29 15:00:00'}, {'dt': 1777485600, 'main': {'temp': 28.97, 'feels_like': 33.42, 'temp_min': 28.97, 'temp_max': 28.97, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 74, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 96}, 'wind': {'speed': 3.91, 'deg': 195, 'gust': 4}, 'visibility': 10000, 'pop': 0.12, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-29 18:00:00'}, {'dt': 1777496400, 'main': {'temp': 28.66, 'feels_like': 33.43, 'temp_min': 28.66, 'temp_max': 28.66, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 78, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.02, 'deg': 192, 'gust': 5.04}, 'visibility': 10000, 'pop': 0.12, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-29 21:00:00'}, {'dt': 1777507200, 'main': {'temp': 28.63, 'feels_like': 32.98, 'temp_min': 28.63, 'temp_max': 28.63, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 76, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.46, 'deg': 197, 'gust': 4.62}, 'visibility': 10000, 'pop': 0.03, 'sys': {'pod': 'n'}, 'dt_txt': '2026-04-30 00:00:00'}, {'dt': 1777518000, 'main': {'temp': 28.74, 'feels_like': 33.06, 'temp_min': 28.74, 'temp_max': 28.74, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.76, 'deg': 205, 'gust': 4.89}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-30 03:00:00'}, {'dt': 1777528800, 'main': {'temp': 28.81, 'feels_like': 33.42, 'temp_min': 28.81, 'temp_max': 28.81, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1012, 'humidity': 76, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.4, 'deg': 220, 'gust': 4.47}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-30 06:00:00'}, {'dt': 1777539600, 'main': {'temp': 28.93, 'feels_like': 33.72, 'temp_min': 28.93, 'temp_max': 28.93, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1011, 'humidity': 76, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 72}, 'wind': {'speed': 4.61, 'deg': 228, 'gust': 4.86}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-30 09:00:00'}, {'dt': 1777550400, 'main': {'temp': 29.14, 'feels_like': 34.04, 'temp_min': 29.14, 'temp_max': 29.14, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1009, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 81}, 'wind': {'speed': 4.64, 'deg': 241, 'gust': 4.82}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-04-30 12:00:00'}], 'city': {'id': 0, 'name': '', 'coord': {'lat': 2.32, 'lon': 48.8589}, 'country': '', 'population': 0, 'timezone': 10800, 'sunrise': 1777084610, 'sunset': 1777128480}}

In [15]:
#---------------------------------- Analysis of the response and the nested dictionaries --------------------------
import json

json_paris_weather=json_paris_weather['list'] # We keep only the list of dictionaries that we need

print(json.dumps(json_paris_weather, indent=4)) # Formatted format for a better readability

[
    {
        "dt": 1777129200,
        "main": {
            "temp": 29,
            "feels_like": 32.73,
            "temp_min": 28.7,
            "temp_max": 29,
            "pressure": 1008,
            "sea_level": 1008,
            "grnd_level": 1009,
            "humidity": 70,
            "temp_kf": 0.3
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10n"
            }
        ],
        "clouds": {
            "all": 87
        },
        "wind": {
            "speed": 3.15,
            "deg": 29,
            "gust": 3.37
        },
        "visibility": 10000,
        "pop": 0.57,
        "rain": {
            "3h": 0.93
        },
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-25 15:00:00"
    },
    {
        "dt": 1777140000,
        "main": {
            "temp": 28.98,
            "feels_like": 32.87,
            "temp_min": 28.9,
            "temp_max": 28.98,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1011,
            "humidity": 71,
            "temp_kf": 0.08
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10n"
            }
        ],
        "clouds": {
            "all": 94
        },
        "wind": {
            "speed": 2.72,
            "deg": 49,
            "gust": 2.98
        },
        "visibility": 10000,
        "pop": 0.54,
        "rain": {
            "3h": 0.23
        },
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-25 18:00:00"
    },
    {
        "dt": 1777150800,
        "main": {
            "temp": 28.54,
            "feels_like": 32.41,
            "temp_min": 28.54,
            "temp_max": 28.54,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 74,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10n"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 2.3,
            "deg": 39,
            "gust": 2.61
        },
        "visibility": 10000,
        "pop": 0.63,
        "rain": {
            "3h": 0.93
        },
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-25 21:00:00"
    },
    {
        "dt": 1777161600,
        "main": {
            "temp": 28.51,
            "feels_like": 32.18,
            "temp_min": 28.51,
            "temp_max": 28.51,
            "pressure": 1008,
            "sea_level": 1008,
            "grnd_level": 1008,
            "humidity": 73,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10n"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 2.67,
            "deg": 17,
            "gust": 2.99
        },
        "visibility": 10000,
        "pop": 0.7,
        "rain": {
            "3h": 1.07
        },
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-26 00:00:00"
    },
    {
        "dt": 1777172400,
        "main": {
            "temp": 28.62,
            "feels_like": 32.08,
            "temp_min": 28.62,
            "temp_max": 28.62,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 71,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10d"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 2.68,
            "deg": 11,
            "gust": 2.59
        },
        "visibility": 10000,
        "pop": 0.75,
        "rain": {
            "3h": 0.19
        },
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-26 03:00:00"
    },
    {
        "dt": 1777183200,
        "main": {
            "temp": 28.54,
            "feels_like": 31.91,
            "temp_min": 28.54,
            "temp_max": 28.54,
            "pressure": 1012,
            "sea_level": 1012,
            "grnd_level": 1012,
            "humidity": 71,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10d"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 1.3,
            "deg": 359,
            "gust": 1.23
        },
        "visibility": 10000,
        "pop": 0.72,
        "rain": {
            "3h": 0.18
        },
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-26 06:00:00"
    },
    {
        "dt": 1777194000,
        "main": {
            "temp": 28.33,
            "feels_like": 31.62,
            "temp_min": 28.33,
            "temp_max": 28.33,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 72,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10d"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 1.02,
            "deg": 320,
            "gust": 1.08
        },
        "visibility": 10000,
        "pop": 0.6,
        "rain": {
            "3h": 0.92
        },
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-26 09:00:00"
    },
    {
        "dt": 1777204800,
        "main": {
            "temp": 28.21,
            "feels_like": 31.52,
            "temp_min": 28.21,
            "temp_max": 28.21,
            "pressure": 1009,
            "sea_level": 1009,
            "grnd_level": 1009,
            "humidity": 73,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10d"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 2.22,
            "deg": 324,
            "gust": 2.54
        },
        "visibility": 10000,
        "pop": 0.74,
        "rain": {
            "3h": 2.86
        },
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-26 12:00:00"
    },
    {
        "dt": 1777215600,
        "main": {
            "temp": 28.6,
            "feels_like": 31.87,
            "temp_min": 28.6,
            "temp_max": 28.6,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 70,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10n"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 2.42,
            "deg": 344,
            "gust": 2.56
        },
        "visibility": 10000,
        "pop": 0.72,
        "rain": {
            "3h": 1.31
        },
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-26 15:00:00"
    },
    {
        "dt": 1777226400,
        "main": {
            "temp": 28.7,
            "feels_like": 32.08,
            "temp_min": 28.7,
            "temp_max": 28.7,
            "pressure": 1011,
            "sea_level": 1011,
            "grnd_level": 1011,
            "humidity": 70,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10n"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 1.71,
            "deg": 49,
            "gust": 2.01
        },
        "visibility": 10000,
        "pop": 0.61,
        "rain": {
            "3h": 0.12
        },
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-26 18:00:00"
    },
    {
        "dt": 1777237200,
        "main": {
            "temp": 28.43,
            "feels_like": 31.52,
            "temp_min": 28.43,
            "temp_max": 28.43,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 70,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 75
        },
        "wind": {
            "speed": 0.62,
            "deg": 144,
            "gust": 0.76
        },
        "visibility": 10000,
        "pop": 0.01,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-26 21:00:00"
    },
    {
        "dt": 1777248000,
        "main": {
            "temp": 28.28,
            "feels_like": 31.37,
            "temp_min": 28.28,
            "temp_max": 28.28,
            "pressure": 1009,
            "sea_level": 1009,
            "grnd_level": 1009,
            "humidity": 71,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 802,
                "main": "Clouds",
                "description": "scattered clouds",
                "icon": "03n"
            }
        ],
        "clouds": {
            "all": 50
        },
        "wind": {
            "speed": 0.8,
            "deg": 235,
            "gust": 0.71
        },
        "visibility": 10000,
        "pop": 0.09,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-27 00:00:00"
    },
    {
        "dt": 1777258800,
        "main": {
            "temp": 28.32,
            "feels_like": 31.6,
            "temp_min": 28.32,
            "temp_max": 28.32,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 72,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10d"
            }
        ],
        "clouds": {
            "all": 81
        },
        "wind": {
            "speed": 1.96,
            "deg": 258,
            "gust": 1.79
        },
        "visibility": 10000,
        "pop": 0.42,
        "rain": {
            "3h": 0.11
        },
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-27 03:00:00"
    },
    {
        "dt": 1777269600,
        "main": {
            "temp": 28.33,
            "feels_like": 31.78,
            "temp_min": 28.33,
            "temp_max": 28.33,
            "pressure": 1012,
            "sea_level": 1012,
            "grnd_level": 1012,
            "humidity": 73,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10d"
            }
        ],
        "clouds": {
            "all": 89
        },
        "wind": {
            "speed": 2.09,
            "deg": 258,
            "gust": 1.95
        },
        "visibility": 10000,
        "pop": 0.49,
        "rain": {
            "3h": 0.16
        },
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-27 06:00:00"
    },
    {
        "dt": 1777280400,
        "main": {
            "temp": 28.54,
            "feels_like": 32.24,
            "temp_min": 28.54,
            "temp_max": 28.54,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 73,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10d"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 3.73,
            "deg": 266,
            "gust": 3.5
        },
        "visibility": 10000,
        "pop": 0.49,
        "rain": {
            "3h": 0.39
        },
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-27 09:00:00"
    },
    {
        "dt": 1777291200,
        "main": {
            "temp": 28.09,
            "feels_like": 31.56,
            "temp_min": 28.09,
            "temp_max": 28.09,
            "pressure": 1008,
            "sea_level": 1008,
            "grnd_level": 1008,
            "humidity": 75,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 501,
                "main": "Rain",
                "description": "moderate rain",
                "icon": "10d"
            }
        ],
        "clouds": {
            "all": 98
        },
        "wind": {
            "speed": 2.67,
            "deg": 283,
            "gust": 2.8
        },
        "visibility": 10000,
        "pop": 0.8,
        "rain": {
            "3h": 3.59
        },
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-27 12:00:00"
    },
    {
        "dt": 1777302000,
        "main": {
            "temp": 28.54,
            "feels_like": 31.91,
            "temp_min": 28.54,
            "temp_max": 28.54,
            "pressure": 1009,
            "sea_level": 1009,
            "grnd_level": 1009,
            "humidity": 71,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10n"
            }
        ],
        "clouds": {
            "all": 83
        },
        "wind": {
            "speed": 1.62,
            "deg": 292,
            "gust": 1.64
        },
        "visibility": 10000,
        "pop": 0.46,
        "rain": {
            "3h": 0.3
        },
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-27 15:00:00"
    },
    {
        "dt": 1777312800,
        "main": {
            "temp": 28.48,
            "feels_like": 31.78,
            "temp_min": 28.48,
            "temp_max": 28.48,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 71,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 77
        },
        "wind": {
            "speed": 0.15,
            "deg": 337,
            "gust": 0.29
        },
        "visibility": 10000,
        "pop": 0.3,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-27 18:00:00"
    },
    {
        "dt": 1777323600,
        "main": {
            "temp": 28.31,
            "feels_like": 31.58,
            "temp_min": 28.31,
            "temp_max": 28.31,
            "pressure": 1009,
            "sea_level": 1009,
            "grnd_level": 1009,
            "humidity": 72,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 804,
                "main": "Clouds",
                "description": "overcast clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 94
        },
        "wind": {
            "speed": 0.56,
            "deg": 207,
            "gust": 0.44
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-27 21:00:00"
    },
    {
        "dt": 1777334400,
        "main": {
            "temp": 28.17,
            "feels_like": 31.29,
            "temp_min": 28.17,
            "temp_max": 28.17,
            "pressure": 1008,
            "sea_level": 1008,
            "grnd_level": 1008,
            "humidity": 72,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 804,
                "main": "Clouds",
                "description": "overcast clouds",
                "icon": "04n"
            }
        ],
        "clouds": {
            "all": 93
        },
        "wind": {
            "speed": 0.71,
            "deg": 194,
            "gust": 0.67
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "n"
        },
        "dt_txt": "2026-04-28 00:00:00"
    },
    {
        "dt": 1777345200,
        "main": {
            "temp": 28.25,
            "feels_like": 31.61,
            "temp_min": 28.25,
            "temp_max": 28.25,
            "pressure": 1009,
            "sea_level": 1009,
            "grnd_level": 1009,
            "humidity": 73,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 803,
                "main": "Clouds",
                "description": "broken clouds",
                "icon": "04d"
            }
        ],
        "clouds": {
            "all": 83
        },
        "wind": {
            "speed": 1.87,
            "deg": 166,
            "gust": 1.83
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-28 03:00:00"
    },
    {
        "dt": 1777356000,
        "main": {
            "temp": 28.44,
            "feels_like": 32.02,
            "temp_min": 28.44,
            "temp_max": 28.44,
            "pressure": 1011,
            "sea_level": 1011,
            "grnd_level": 1011,
            "humidity": 73,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 804,
                "main": "Clouds",
                "description": "overcast clouds",
                "icon": "04d"
            }
        ],
        "clouds": {
            "all": 90
        },
        "wind": {
            "speed": 2.28,
            "deg": 199,
            "gust": 2.16
        },
        "visibility": 10000,
        "pop": 0,
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-28 06:00:00"
    },
    {
        "dt": 1777366800,
        "main": {
            "temp": 28.55,
            "feels_like": 32.26,
            "temp_min": 28.55,
            "temp_max": 28.55,
            "pressure": 1010,
            "sea_level": 1010,
            "grnd_level": 1010,
            "humidity": 73,
            "temp_kf": 0
        },
        "weather": [
            {
                "id": 500,
                "main": "Rain",
                "description": "light rain",
                "icon": "10d"
            }
        ],
        "clouds": {
            "all": 100
        },
        "wind": {
            "speed": 2.27,
            "deg": 232,
            "gust": 2.23
        },
        "visibility": 10000,
        "pop": 0.24,
        "rain": {
            "3h": 0.16
        },
        "sys": {
            "pod": "d"
        },
        "dt_txt": "2026-04-28 09:00:00"
    },
    {
        "dt": 1777377600,
        "main": {
            "temp": 28.78,

In [16]:
#--------------------------------- Load the data into a dataframe ---------------------------------

# Our Json response contains nested dictionaries so we will use json_normalize to flatten it in order 
# to use it to create a dataframe.

RECORD_PATH = "weather" #record_path`: The key inside each dictionary that points to the LIST of items we 
#want to flatten.


META_FIELDS = [
        'dt',
        ["main","temp"],
        ["main","feels_like"],
        ["main","temp_min"],
        ["main","temp_max"],
        ["main","pressure"],
        ["main","sea_level"],
        ["main","grnd_level"],
        ["main","humidity"],
        ["main","temp_kf"],
        ["clouds","all"],
        ["wind","speed"],
        ["wind","deg"],
        ["wind","gust"],
        "visibility",
        "pop",
        ["sys","pop"],
        "dt_txt"
        ] # `meta`: A list of keys from the *parent* dictionary that 
#we want to keep and repeat for each flattened record.

json_normalized_paris_weather = pd.json_normalize(
data=json_paris_weather,
record_path=RECORD_PATH,
meta=META_FIELDS,
errors='ignore'  # This is important for handling missing/empty lists
)

# Creation of the dataframe
display(json_normalized_paris_weather) # We don't do pd.datatframe() because the normalized json is already a dataframe, we just need to display it

,id,main,description,icon,dt,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,...,main.humidity,main.temp_kf,clouds.all,wind.speed,wind.deg,wind.gust,visibility,pop,sys.pop,dt_txt
0,500,Rain,light rain,10n,1777129200,29,32.73,28.7,29,1008,...,70,0.3,87,3.15,29,3.37,10000,0.57,NaN,2026-04-25 15:00:00
1,500,Rain,light rain,10n,1777140000,28.98,32.87,28.9,28.98,1010,...,71,0.08,94,2.72,49,2.98,10000,0.54,NaN,2026-04-25 18:00:00
2,500,Rain,light rain,10n,1777150800,28.54,32.41,28.54,28.54,1010,...,74,0,100,2.3,39,2.61,10000,0.63,NaN,2026-04-25 21:00:00
3,500,Rain,light rain,10n,1777161600,28.51,32.18,28.51,28.51,1008,...,73,0,100,2.67,17,2.99,10000,0.7,NaN,2026-04-26 00:00:00
4,500,Rain,light rain,10d,1777172400,28.62,32.08,28.62,28.62,1010,...,71,0,100,2.68,11,2.59,10000,0.75,NaN,2026-04-26 03:00:00
5,500,Rain,light rain,10d,1777183200,28.54,31.91,28.54,28.54,1012,...,71,0,100,1.3,359,1.23,10000,0.72,NaN,2026-04-26 06:00:00
6,500,Rain,light rain,10d,1777194000,28.33,31.62,28.33,28.33,1010,...,72,0,100,1.02,320,1.08,10000,0.6,NaN,2026-04-26 09:00:00
7,500,Rain,light rain,10d,1777204800,28.21,31.52,28.21,28.21,1009,...,73,0,100,2.22,324,2.54,10000,0.74,NaN,2026-04-26 12:00:00
8,500,Rain,light rain,10n,1777215600,28.6,31.87,28.6,28.6,1010,...,70,0,100,2.42,344,2.56,10000,0.72,NaN,2026-04-26 15:00:00
9,500,Rain,light rain,10n,1777226400,28.7,32.08,28.7,28.7,1011,...,70,0,100,1.71,49,2.01,10000,0.61,NaN,2026-04-26 18:00:00
10,803,Clouds,broken clouds,04n,1777237200,28.43,31.52,28.43,28.43,1010,...,70,0,75,0.62,144,0.76,10000,0.01,NaN,2026-04-26 21:00:00
11,802,Clouds,scattered clouds,03n,1777248000,28.28,31.37,28.28,28.28,1009,...,71,0,50,0.8,235,0.71,10000,0.09,NaN,2026-04-27 00:00:00
12,500,Rain,light rain,10d,1777258800,28.32,31.6,28.32,28.32,1010,...,72,0,81,1.96,258,1.79,10000,0.42,NaN,2026-04-27 03:00:00
13,500,Rain,light rain,10d,1777269600,28.33,31.78,28.33,28.33,1012,...,73,0,89,2.09,258,1.95,10000,0.49,NaN,2026-04-27 06:00:00
14,500,Rain,light rain,10d,1777280400,28.54,32.24,28.54,28.54,1010,...,73,0,100,3.73,266,3.5,10000,0.49,NaN,2026-04-27 09:00:00
15,501,Rain,moderate rain,10d,1777291200,28.09,31.56,28.09,28.09,1008,...,75,0,98,2.67,283,2.8,10000,0.8,NaN,2026-04-27 12:00:00
16,500,Rain,light rain,10n,1777302000,28.54,31.91,28.54,28.54,1009,...,71,0,83,1.62,292,1.64,10000,0.46,NaN,2026-04-27 15:00:00
17,803,Clouds,broken clouds,04n,1777312800,28.48,31.78,28.48,28.48,1010,...,71,0,77,0.15,337,0.29,10000,0.3,NaN,2026-04-27 18:00:00
18,804,Clouds,overcast clouds,04n,1777323600,28.31,31.58,28.31,28.31,1009,...,72,0,94,0.56,207,0.44,10000,0,NaN,2026-04-27 21:00:00
19,804,Clouds,overcast clouds,04n,1777334400,28.17,31.29,28.17,28.17,1008,...,72,0,93,0.71,194,0.67,10000,0,NaN,2026-04-28 00:00:00
20,803,Clouds,broken clouds,04d,1777345200,28.25,31.61,28.25,28.25,1009,...,73,0,83,1.87,166,1.83,10000,0,NaN,2026-04-28 03:00:00
21,804,Clouds,overcast clouds,04d,1777356000,28.44,32.02,28.44,28.44,1011,...,73,0,90,2.28,199,2.16,10000,0,NaN,2026-04-28 06:00:00
22,500,Rain,light rain,10d,1777366800,28.55,32.26,28.55,28.55,1010,...,73,0,100,2.27,232,2.23,10000,0.24,NaN,2026-04-28 09:00:00
23,500,Rain,light rain,10d,1777377600,28.78,32.61,28.78,28.78,1008,...,72,0,100,2.67,246,2.52,10000,0.33,NaN,2026-04-28 12:00:00
24,804,Clouds,overcast clouds,04n,1777388400,28.9,32.88,28.9,28.9,1009,...,72,0,92,2.4,226,2.26,10000,0.09,NaN,2026-04-28 15:00:00
25,804,Clouds,overcast clouds,04n,1777399200,28.81,32.86,28.81,28.81,1010,...,73,0,90,2.83,196,2.76,10000,0.05,NaN,2026-04-28 18:00:00
26,804,Clouds,overcast clouds,04n,1777410000,28.61,32.57,28.61,28.61,1009,...,74,0,100,2.98,209,2.82,10000,0,NaN,2026-04-28 21:00:00
27,804,Clouds,overcast clouds,04n,1777420800,28.51,32.52,28.51,28.51,1008,...,75,0,100,3.15,224,3.04,10000,0,NaN,2026-04-29 00:00:00
28,804,Clouds,overcast clouds,04d,1777431600,28.57,32.66,28.57,28.57,1010,...,75,0,100,3.6,209,3.49,10000,0.12,NaN,2026-04-29 03:00:00
29,804,Clouds,overcast clouds,04d,1777442400,28.76,33.11,28.76,28.76,1011,...,75,0,100,4.3,219,4.17,10000,0.12,NaN,2026-04-29 06:00:00
30,804,Clouds,overcast clouds,04d,1777453200,29,33.49,29,29,1010,...,74,0,100,4.25,230,4.3,10000,0.05,NaN,2026-04-29 09:00:00
31,804,Clouds,overcast clouds,04d,1777464000,29.01,33.52,29.01,29.01,1009,...,74,0,96,3.88,237,3.85,10000,0.19,NaN,2026-04-29 12:00:00
32,804,Clouds,overcast clouds,04n,1777474800,29.03,33.37,29.03,29.03,1010,...,73,0,92,3.46,221,3.39,10000,0.08,NaN,2026-04-29 15:00:00
33,804,Clouds,overcast clouds,04n,1777485600,28.97,33.42,28.97,28.97,1011,...,74,0,96,3.91,195,4,10000,0.12,NaN,2026-04-29 18:00:00
34,804,Clouds,overcast clouds,04n,1777496400,28.66,33.43,28.66,28.66,1011,...,78,0,100,5.02,192,5.04,10000,0.12,NaN,2026-04-29 21:00:00
35,804,Clouds,overcast clouds,04n,1777507200,28.63,32.98,28.63,28.63,1009,...,76,0,100,4.46,197,4.62,10000,0.03,NaN,2026-04-30 00:00:00
36,804,Clouds,overcast clouds,04d,1777518000,28.74,33.06,28.74,28.74,1011,...,75,0,100,4.76,205,4.89,10000,0,NaN,2026-04-30 03:00:00
37,804,Clouds,overcast clouds,04d,1777528800,28.81,33.42,28.81,28.81,1012,...,76,0,100,4.4,220,4.47,10000,0,NaN,2026-04-30 06:00:00
38,803,Clouds,broken clouds,04d,1777539600,28.93,33.72,28.93,28.93,1011,...,76,0,72,4.61,228,4.86,10000,0,NaN,2026-04-30 09:00:00
39,803,Clouds,broken clouds,04d,1777550400,29.14,34.04,29.14,29.14,1009,...,75,0,81,4.64,241,4.82,10000,0,NaN,2026-04-30 12:00:00

**List of variable in the json response and the data frame that we wish to keep (checked variables):**

Variables not nested:
- [ ] **`dt`** : Time of data forecasted, unix, UTC
- [x] **`visibility`**: Average visibility (meter) 
- [x] **`pop`**: Probability of precipitation (0 to 1 where 0=0% and 1=100%) 
- [x] **`dt_txt`** #  Time of data forecasted, ISO, UTC 


Variables in **`main`** : 
- [x] **`temp`** : Temperature (°C) 
- [x] **`feels_like`**: Human perception of the temperature (°C) 
- [x] **`temp_min`**: Minimum temperature at the moment of calculation (°C) . This is minimal forecasted temperature (within large megalopolises and urban areas), use this parameter optionally.
- [x] **`temp_max`**: Maximum temperature at the moment of calculation (°C).  This is minimal forecasted temperature (within large megalopolises and urban areas), use this parameter optionally.
- [ ] **`pressure`**: Atmospheric pressure on the sea level (hPa)
- [ ] **`sea_level`**: Atmospheric pressure on the sea level (hPa)
- [ ] **`grnd_level`**: Atmospheric pressure on the ground level (hPa)
- [x] **`humidity`**: Humidity % 
- [ ] **`temp_kf`**: Internal parameter

Variables in **`weather`** : 
- [ ] **`id`**: Weather condition id
- [ ] **`main`**: Group of weather parameters (Rain, Snow, Clouds etc.)
- [x] **`description`**: Weather condition within the group 
- [ ] **`icon`**: Weather icon id
  
Variable in **`cloud`** : 
- [x] **`all`**: Cloudiness, %

Variables in **`wind`**:
- [x] **`speed`**: Wind speed (meter/sec) 
- [ ] **`deg`**: Wind direction (degree)
- [x] **`gust`**: Wind gust (meter/sec) 

Variable in **`sys`** : 
- [x] **`pop`**: Part of the day (n=night, d=day)

In [17]:
#----------------------------------- Selection of columns of interest -------------------------------------

columns_to_keep=['dt_txt','main.temp','main.feels_like','main.temp_min','main.temp_max','main.humidity','description','clouds.all','pop','sys.pop','wind.speed','wind.gust','visibility']
df_weather_paris= json_normalized_paris_weather[columns_to_keep].copy()

display(df_weather_paris)

,dt_txt,main.temp,main.feels_like,main.temp_min,main.temp_max,main.humidity,description,clouds.all,pop,sys.pop,wind.speed,wind.gust,visibility
0,2026-04-25 15:00:00,29,32.73,28.7,29,70,light rain,87,0.57,NaN,3.15,3.37,10000
1,2026-04-25 18:00:00,28.98,32.87,28.9,28.98,71,light rain,94,0.54,NaN,2.72,2.98,10000
2,2026-04-25 21:00:00,28.54,32.41,28.54,28.54,74,light rain,100,0.63,NaN,2.3,2.61,10000
3,2026-04-26 00:00:00,28.51,32.18,28.51,28.51,73,light rain,100,0.7,NaN,2.67,2.99,10000
4,2026-04-26 03:00:00,28.62,32.08,28.62,28.62,71,light rain,100,0.75,NaN,2.68,2.59,10000
5,2026-04-26 06:00:00,28.54,31.91,28.54,28.54,71,light rain,100,0.72,NaN,1.3,1.23,10000
6,2026-04-26 09:00:00,28.33,31.62,28.33,28.33,72,light rain,100,0.6,NaN,1.02,1.08,10000
7,2026-04-26 12:00:00,28.21,31.52,28.21,28.21,73,light rain,100,0.74,NaN,2.22,2.54,10000
8,2026-04-26 15:00:00,28.6,31.87,28.6,28.6,70,light rain,100,0.72,NaN,2.42,2.56,10000
9,2026-04-26 18:00:00,28.7,32.08,28.7,28.7,70,light rain,100,0.61,NaN,1.71,2.01,10000
10,2026-04-26 21:00:00,28.43,31.52,28.43,28.43,70,broken clouds,75,0.01,NaN,0.62,0.76,10000
11,2026-04-27 00:00:00,28.28,31.37,28.28,28.28,71,scattered clouds,50,0.09,NaN,0.8,0.71,10000
12,2026-04-27 03:00:00,28.32,31.6,28.32,28.32,72,light rain,81,0.42,NaN,1.96,1.79,10000
13,2026-04-27 06:00:00,28.33,31.78,28.33,28.33,73,light rain,89,0.49,NaN,2.09,1.95,10000
14,2026-04-27 09:00:00,28.54,32.24,28.54,28.54,73,light rain,100,0.49,NaN,3.73,3.5,10000
15,2026-04-27 12:00:00,28.09,31.56,28.09,28.09,75,moderate rain,98,0.8,NaN,2.67,2.8,10000
16,2026-04-27 15:00:00,28.54,31.91,28.54,28.54,71,light rain,83,0.46,NaN,1.62,1.64,10000
17,2026-04-27 18:00:00,28.48,31.78,28.48,28.48,71,broken clouds,77,0.3,NaN,0.15,0.29,10000
18,2026-04-27 21:00:00,28.31,31.58,28.31,28.31,72,overcast clouds,94,0,NaN,0.56,0.44,10000
19,2026-04-28 00:00:00,28.17,31.29,28.17,28.17,72,overcast clouds,93,0,NaN,0.71,0.67,10000
20,2026-04-28 03:00:00,28.25,31.61,28.25,28.25,73,broken clouds,83,0,NaN,1.87,1.83,10000
21,2026-04-28 06:00:00,28.44,32.02,28.44,28.44,73,overcast clouds,90,0,NaN,2.28,2.16,10000
22,2026-04-28 09:00:00,28.55,32.26,28.55,28.55,73,light rain,100,0.24,NaN,2.27,2.23,10000
23,2026-04-28 12:00:00,28.78,32.61,28.78,28.78,72,light rain,100,0.33,NaN,2.67,2.52,10000
24,2026-04-28 15:00:00,28.9,32.88,28.9,28.9,72,overcast clouds,92,0.09,NaN,2.4,2.26,10000
25,2026-04-28 18:00:00,28.81,32.86,28.81,28.81,73,overcast clouds,90,0.05,NaN,2.83,2.76,10000
26,2026-04-28 21:00:00,28.61,32.57,28.61,28.61,74,overcast clouds,100,0,NaN,2.98,2.82,10000
27,2026-04-29 00:00:00,28.51,32.52,28.51,28.51,75,overcast clouds,100,0,NaN,3.15,3.04,10000
28,2026-04-29 03:00:00,28.57,32.66,28.57,28.57,75,overcast clouds,100,0.12,NaN,3.6,3.49,10000
29,2026-04-29 06:00:00,28.76,33.11,28.76,28.76,75,overcast clouds,100,0.12,NaN,4.3,4.17,10000
30,2026-04-29 09:00:00,29,33.49,29,29,74,overcast clouds,100,0.05,NaN,4.25,4.3,10000
31,2026-04-29 12:00:00,29.01,33.52,29.01,29.01,74,overcast clouds,96,0.19,NaN,3.88,3.85,10000
32,2026-04-29 15:00:00,29.03,33.37,29.03,29.03,73,overcast clouds,92,0.08,NaN,3.46,3.39,10000
33,2026-04-29 18:00:00,28.97,33.42,28.97,28.97,74,overcast clouds,96,0.12,NaN,3.91,4,10000
34,2026-04-29 21:00:00,28.66,33.43,28.66,28.66,78,overcast clouds,100,0.12,NaN,5.02,5.04,10000
35,2026-04-30 00:00:00,28.63,32.98,28.63,28.63,76,overcast clouds,100,0.03,NaN,4.46,4.62,10000
36,2026-04-30 03:00:00,28.74,33.06,28.74,28.74,75,overcast clouds,100,0,NaN,4.76,4.89,10000
37,2026-04-30 06:00:00,28.81,33.42,28.81,28.81,76,overcast clouds,100,0,NaN,4.4,4.47,10000
38,2026-04-30 09:00:00,28.93,33.72,28.93,28.93,76,broken clouds,72,0,NaN,4.61,4.86,10000
39,2026-04-30 12:00:00,29.14,34.04,29.14,29.14,75,broken clouds,81,0,NaN,4.64,4.82,10000

**3.2 Function for API calls and data preparation**

To call the weather API for each city, we are going to create a function that will request the API and save all the relevant information we have previously identified.

In [18]:
def fetch_weather_data(cities_df):
    """Fetch 7-day weather forecast for each city."""
    
    load_dotenv()
    API_KEY = os.getenv("API_KEY")
    
    if not API_KEY:
        raise ValueError("API_KEY not found in .env file")
    
    url_base = "https://api.openweathermap.org/data/2.5/forecast"
    results = {}
    
    for _, row in cities_df.iterrows():
        city = row['City']
        
        params = {
            "lat": row['Latitude'],
            "lon": row['Longitude'],
            "units": "metric",
            "appid": API_KEY
        }
        
        try:
            response = requests.get(url_base, params=params, timeout=10)
            
            if response.status_code != 200:
                results[city] = (pd.DataFrame(), False)
                continue
            
            # Parse and flatten JSON
            forecast_list = response.json()['list']
            df = pd.json_normalize(forecast_list, errors='ignore')
            
            # Extract weather description
            df['description'] = df['weather'].apply(
                lambda x: x[0]['description'] if isinstance(x, list) and len(x) > 0 else None
            )
            
            # Select and rename columns
            cols_to_keep = {
                'main.temp': 'temp',
                'main.temp_min': 'temp_min',
                'main.temp_max': 'temp_max',
                'main.humidity': 'humidity',
                'pop': 'rain_probability',
                'clouds.all': 'cloudiness',
                'wind.speed': 'wind_speed'
            }
            
            existing_cols = [col for col in cols_to_keep.keys() if col in df.columns]
            weather_df = df[['dt_txt', 'description'] + existing_cols].rename(columns=cols_to_keep)
            
            # Convert types
            weather_df['dt_txt'] = pd.to_datetime(weather_df['dt_txt'])
            for col in weather_df.columns:
                if col not in ['dt_txt', 'description']:
                    weather_df[col] = pd.to_numeric(weather_df[col], errors='coerce')        
            results[city] = (weather_df, True)
            
        except Exception as e:
            results[city] = (pd.DataFrame(), False)
    
    return results

**3.3 Weather API call for all cities**

Now we can use the created function to extract the weather information of the weather forecast for our list of 35 cities.

In [19]:
weather_all_cities_dict = fetch_weather_data(df_coord_35_cities)

In [20]:
weather_all_cities_dict

{'Mont Saint Michel': (                dt_txt       description   temp  temp_min  temp_max  humidity  \
  0  2026-04-25 15:00:00     broken clouds  19.06     18.73     19.06        58
  1  2026-04-25 18:00:00  scattered clouds  17.36     16.43     17.36        71
  2  2026-04-25 21:00:00        few clouds  12.12     12.12     12.12        86
  3  2026-04-26 00:00:00  scattered clouds  10.14     10.14     10.14        77
  4  2026-04-26 03:00:00   overcast clouds   9.32      9.32      9.32        80
  5  2026-04-26 06:00:00     broken clouds   9.74      9.74      9.74        80
  6  2026-04-26 09:00:00   overcast clouds  15.45     15.45     15.45        64
  7  2026-04-26 12:00:00   overcast clouds  18.41     18.41     18.41        56
  8  2026-04-26 15:00:00   overcast clouds  18.14     18.14     18.14        59
  9  2026-04-26 18:00:00   overcast clouds  15.70     15.70     15.70        76
  10 2026-04-26 21:00:00   overcast clouds  12.49     12.49     12.49        76
  11 2026-04-27 00:00:00   overcast clouds  10.95     10.95     10.95        76
  12 2026-04-27 03:00:00   overcast clouds  10.22     10.22     10.22        70
  13 2026-04-27 06:00:00   overcast clouds  10.02     10.02     10.02        71
  14 2026-04-27 09:00:00   overcast clouds  15.50     15.50     15.50        67
  15 2026-04-27 12:00:00   overcast clouds  18.68     18.68     18.68        52
  16 2026-04-27 15:00:00   overcast clouds  18.63     18.63     18.63        55
  17 2026-04-27 18:00:00   overcast clouds  14.38     14.38     14.38        72
  18 2026-04-27 21:00:00   overcast clouds   9.30      9.30      9.30        82
  19 2026-04-28 00:00:00   overcast clouds   8.15      8.15      8.15        78
  20 2026-04-28 03:00:00     broken clouds   8.22      8.22      8.22        79
  21 2026-04-28 06:00:00     broken clouds   8.77      8.77      8.77        77
  22 2026-04-28 09:00:00         clear sky  14.26     14.26     14.26        65
  23 2026-04-28 12:00:00         clear sky  17.20     17.20     17.20        56
  24 2026-04-28 15:00:00         clear sky  16.21     16.21     16.21        62
  25 2026-04-28 18:00:00         clear sky  12.94     12.94     12.94        79
  26 2026-04-28 21:00:00         clear sky   9.88      9.88      9.88        88
  27 2026-04-29 00:00:00         clear sky   9.08      9.08      9.08        88
  28 2026-04-29 03:00:00         clear sky   7.39      7.39      7.39        90
  29 2026-04-29 06:00:00         clear sky   7.26      7.26      7.26        82
  30 2026-04-29 09:00:00         clear sky  12.02     12.02     12.02        63
  31 2026-04-29 12:00:00         clear sky  15.89     15.89     15.89        53
  32 2026-04-29 15:00:00         clear sky  17.57     17.57     17.57        55
  33 2026-04-29 18:00:00         clear sky  15.47     15.47     15.47        64
  34 2026-04-29 21:00:00         clear sky  13.06     13.06     13.06        63
  35 2026-04-30 00:00:00         clear sky  10.67     10.67     10.67        69
  36 2026-04-30 03:00:00         clear sky   8.58      8.58      8.58        72
  37 2026-04-30 06:00:00         clear sky   8.69      8.69      8.69        72
  38 2026-04-30 09:00:00         clear sky  14.98     14.98     14.98        54
  39 2026-04-30 12:00:00         clear sky  18.60     18.60     18.60        45

      rain_probability  cloudiness  wind_speed
  0                  0          75        4.01
  1                  0          44        3.28
  2                  0          18        3.58
  3                  0          29        2.02
  4                  0          89        2.45
  5                  0          84        2.10
  6                  0          89        2.19
  7                  0          95        0.70
  8                  0         100        2.38
  9                  0          99        2.38
  10                 0         100        3.51
  11                 0         100        2.64
  12                 0         100        1.46
  13                 0         100        2.08
  14                 0         100        2.84
  15                 0         100        2.98
  16                 0          95        5.24
  17                 0          99        5.04
  18                 0          98        3.60
  19                 0         100        3.86
  20                 0          81        3.58
  21                 0          76        2.85
  22                 0           3        6.77
  23                 0           5        7.11
  24                 0           2        8.60
  25                 0           3        7.36
  26                 0           1        6.54
  27                 0           0        5.53
  28                 0           0        5.23
  29                 0           0        5.87
  30                 0           0        7.75
  31                 0           0        8.02
  32                 0           0        7.73
  33                 0           0        6.78
  34                 0           0        6.95
  35                 0           0        5.01
  36                 0           0        4.57
  37                 0           0        4.82
  38                 0           0        6.38
  39                 0           0        6.11  ,
  True),
 'St Malo': (                dt_txt       description   temp  temp_min  temp_max  humidity  \
  0  2026-04-25 15:00:00   overcast clouds   2.94      2.94      4.56        57
  1  2026-04-25 18:00:00   overcast clouds   4.92      4.92      6.31        45
  2  2026-04-25 21:00:00   overcast clouds   8.33      8.33      8.33        27
  3  2026-04-26 00:00:00   overcast clouds   8.26      8.26      8.26        31
  4  2026-04-26 03:00:00     broken clouds   4.11      4.11      4.11        40
  5  2026-04-26 06:00:00  scattered clouds   2.88      2.88      2.88        45
  6  2026-04-26 09:00:00        few clouds   1.26      1.26      1.26        49
  7  2026-04-26 12:00:00  scattered clouds   0.61      0.61      0.61        54
  8  2026-04-26 15:00:00        few clouds   5.91      5.91      5.91        38
  9  2026-04-26 18:00:00        few clouds  10.14     10.14     10.14        29
  10 2026-04-26 21:00:00         clear sky  12.37     12.37     12.37        28
  11 2026-04-27 00:00:00        few clouds  12.05     12.05     12.05        30
  12 2026-04-27 03:00:00   overcast clouds   8.25      8.25      8.25        41
  13 2026-04-27 06:00:00   overcast clouds   6.44      6.44      6.44        46
  14 2026-04-27 09:00:00   overcast clouds   5.81      5.81      5.81        50
  15 2026-04-27 12:00:00   overcast clouds   4.15      4.15      4.15        55
  16 2026-04-27 15:00:00   overcast clouds   6.91      6.91      6.91        56
  17 2026-04-27 18:00:00   overcast clouds   9.88      9.88      9.88        42
  18 2026-04-27 21:00:00   overcast clouds   9.87      9.87      9.87        33
  19 2026-04-28 00:00:00   overcast clouds   8.07      8.07      8.07        39
  20 2026-04-28 03:00:00     broken clouds   4.22      4.22      4.22        46
  21 2026-04-28 06:00:00  scattered clouds   1.96      1.96      1.96        63
  22 2026-04-28 09:00:00         clear sky   0.36      0.36      0.36        70
  23 2026-04-28 12:00:00         clear sky  -0.26     -0.26     -0.26        71
  24 2026-04-28 15:00:00         clear sky   3.77      3.77      3.77        52
  25 2026-04-28 18:00:00         clear sky   7.85      7.85      7.85        40
  26 2026-04-28 21:00:00         clear sky   9.65      9.65      9.65        36
  27 2026-04-29 00:00:00         clear sky   8.13      8.13      8.13        38
  28 2026-04-29 03:00:00        few clouds   3.85      3.85      3.85        56
  29 2026-04-29 06:00:00  scattered clouds   1.02      1.02      1.02        63
  30 2026-04-29 09:00:00     broken clouds  -0.53     -0.53     -0.53        69
  31 2026-04-29 12:00:00  scattered clouds  -1.18     -1.18     -1.18        72
  32 2026-04-29 15:00:00        few clouds   3.47      3.47      3.47        55
  33 2026-04-29 18:00:00  scattered clouds   6.78      6.78      6.78        46
  34 2026-04-29 21:00:00   overcast clouds   7.86      7.86      7.86        39
  35 2026-04-30 00:00:00     broken clouds   7.31      7.31      7.31        39
  36 2026-04-30 03:00:00  scattered clouds   3.17      3.17      3.17        57
  37 2026-04-30 06:00:00        few clouds   0.65      0.65      0.65        63
  38 2026-04-30 09:00:00         clear sky  -1.43     -1.43     -1.43        72
  39 2026-04-30 12:00:00         clear sky  -1.55     -1.55     -1.55        77

      rain_probability  cloudiness  wind_speed
  0                  0          91        3.69
  1                  0          92        6.61
  2                  0         100        6.52
  3                  0         100        5.66
  4                  0          64        2.35
  5                  0          33        1.92
  6                  0          17        1.92
  7                  0          44        1.80
  8                  0          15        2.54
  9                  0          12        4.81
  10                 0           2        4.80
  11                 0          13        2.89
  12                 0         100        3.26
  13                 0         100        3.28
  14                 0         100        3.51
  15                 0         100        6.44
  16                 0         100        7.32
  17                 0         100        7.47
  18                 0         100        7.79
  19                 0         100        7.48
  20                 0          84        6.96
  21                 0          44        6.98
  22                 0           0        6.02
  23                 0           3        5.20
  24                 0           6        6.74
  25                 0           7        6.19
  26                 0           5        6.82
  27                 0           8        6.11
  28                 0          12        3.42
  29                 0          47        3.50
  30                 0          67        2.70
  31                 0          43        2.52
  32                 0          14        4.32
  33                 0          41        5.39
  34                 0          90        5.40
  35                 0          70        5.37
  36                 0          45        3.56
  37                 0          24        4.22
  38                 0           0        3.04
  39                 0           1        2.63  ,
  True),
 'Bayeux': (                dt_txt       description   temp  temp_min  temp_max  humidity  \
  0  2026-04-25 15:00:00   overcast clouds  18.85     16.27     18.85        60
  1  2026-04-25 18:00:00     broken clouds  15.39     13.01     15.39        74
  2  2026-04-25 21:00:00         clear sky   9.81      9.81      9.81        87
  3  2026-04-26 00:00:00  scattered clouds   8.43      8.43      8.43        90
  4  2026-04-26 03:00:00   overcast clouds   6.85      6.85      6.85        91
  5  2026-04-26 06:00:00   overcast clouds   8.58      8.58      8.58        83
  6  2026-04-26 09:00:00   overcast clouds  14.22     14.22     14.22        62
  7  2026-04-26 12:00:00   overcast clouds  16.30     16.30     16.30        57
  8  2026-04-26 15:00:00   overcast clouds  16.30     16.30     16.30        60
  9  2026-04-26 18:00:00   overcast clouds  12.19     12.19     12.19        79
  10 2026-04-26 21:00:00   overcast clouds   9.84      9.84      9.84        89
  11 2026-04-27 00:00:00   overcast clouds   9.05      9.05      9.05        84
  12 2026-04-27 03:00:00   overcast clouds   8.32      8.32      8.32        84
  13 2026-04-27 06:00:00   overcast clouds   9.53      9.53      9.53        86
  14 2026-04-27 09:00:00   overcast clouds  14.11     14.11     14.11        74
  15 2026-04-27 12:00:00     broken clouds  15.13     15.13     15.13        65
  16 2026-04-27 15:00:00  scattered clouds  14.25     14.25     14.25        68
  17 2026-04-27 18:00:00     broken clouds  11.89     11.89     11.89        81
  18 2026-04-27 21:00:00     broken clouds   9.08      9.08      9.08        83
  19 2026-04-28 00:00:00     broken clouds   9.15      9.15      9.15        88
  20 2026-04-28 03:00:00  scattered clouds   8.68      8.68      8.68        88
  21 2026-04-28 06:00:00  scattered clouds   9.69      9.69      9.69        85
  22 2026-04-28 09:00:00  scattered clouds  12.41     12.41     12.41        81
  23 2026-04-28 12:00:00        few clouds  13.40     13.40     13.40        76
  24 2026-04-28 15:00:00     broken clouds  12.23     12.23     12.23        79
  25 2026-04-28 18:00:00     broken clouds  10.83     10.83     10.83        86
  26 2026-04-28 21:00:00         clear sky  10.04     10.04     10.04        90
  27 2026-04-29 00:00:00         clear sky   9.36      9.36      9.36        86
  28 2026-04-29 03:00:00         clear sky   8.16      8.16      8.16        83
  29 2026-04-29 06:00:00         clear sky   8.40      8.40      8.40        75
  30 2026-04-29 09:00:00         clear sky  11.42     11.42     11.42        64
  31 2026-04-29 12:00:00         clear sky  13.84     13.84     13.84        63
  32 2026-04-29 15:00:00         clear sky  13.96     13.96     13.96        68
  33 2026-04-29 18:00:00         clear sky  11.83     11.83     11.83        82
  34 2026-04-29 21:00:00         clear sky  11.05     11.05     11.05        82
  35 2026-04-30 00:00:00         clear sky   9.60      9.60      9.60        79
  36 2026-04-30 03:00:00         clear sky   6.71      6.71      6.71        82
  37 2026-04-30 06:00:00         clear sky   7.46      7.46      7.46        78
  38 2026-04-30 09:00:00         clear sky  13.40     13.40     13.40        60
  39 2026-04-30 12:00:00         clear sky  16.31     16.31     16.31        56

      rain_probability  cloudiness  wind_speed
  0                  0          85        3.83
  1                  0          55        2.83
  2                  0           9        2.54
  3                  0          39        2.38
  4                  0          91        3.15
  5                  0          96        3.23
  6                  0          89        3.77
  7                  0          95        3.93
  8                  0         100        3.67
  9                  0         100        3.32
  10                 0          99        3.48
  11                 0          99        2.66
  12                 0         100        1.56
  13                 0         100        1.98
  14                 0          95        3.82
  15                 0          67        4.76
  16                 0          25        4.94
  17                 0          52        2.98
  18                 0          66        3.37
  19                 0          52        3.07
  20                 0          34        3.03
  21                 0          37        5.06
  22                 0          33        7.48
  23                 0          14        7.94
  24                 0          64        9.77
  25                 0          62        8.76
  26                 0           0        8.65
  27                 0           1        7.30
  28                 0           0        6.24
  29                 0           0        7.52
  30                 0           0        8.62
  31                 0           0        9.00
  32                 0           0        9.75
  33                 0           0        8.44
  34                 0           0        7.51
  35                 0           0        6.53
  36                 0           0        4.41
  37                 0           0        3.94
  38                 0           3        6.57
  39                 0           2        7.06  ,
  True),
 'Le Havre': (                dt_txt       description   temp  temp_min  temp_max  humidity  \
  0  2026-04-25 15:00:00  scattered clouds  17.80     14.39     17.80        46
  1  2026-04-25 18:00:00  scattered clouds  16.04     14.30     16.04        62
  2  2026-04-25 21:00:00         clear sky  11.96     11.96     11.96        72
  3  2026-04-26 00:00:00         clear sky  11.07     11.07     11.07        72
  4  2026-04-26 03:00:00   overcast clouds  10.19     10.19     10.19        73
  5  2026-04-26 06:00:00   overcast clouds  10.00     10.00     10.00        70
  6  2026-04-26 09:00:00   overcast clouds  13.60     13.60     13.60        57
  7  2026-04-26 12:00:00   overcast clouds  16.14     16.14     16.14        50
  8  2026-04-26 15:00:00   overcast clouds  16.80     16.80     16.80        50
  9  2026-04-26 18:00:00   overcast clouds  15.31     15.31     15.31        64
  10 2026-04-26 21:00:00   overcast clouds  11.85     11.85     11.85        74
  11 2026-04-27 00:00:00   overcast clouds  11.46     11.46     11.46        76
  12 2026-04-27 03:00:00   overcast clouds  11.18     11.18     11.18        78
  13 2026-04-27 06:00:00   overcast clouds  11.14     11.14     11.14        76
  14 2026-04-27 09:00:00   overcast clouds  13.87     13.87     13.87        69
  15 2026-04-27 12:00:00     broken clouds  14.77     14.77     14.77        66
  16 2026-04-27 15:00:00        few clouds  14.11     14.11     14.11        68
  17 2026-04-27 18:00:00     broken clouds  13.49     13.49     13.49        69
  18 2026-04-27 21:00:00         clear sky  11.38     11.38     11.38        71
  19 2026-04-28 00:00:00         clear sky  10.86     10.86     10.86        75
  20 2026-04-28 03:00:00         clear sky   9.87      9.87      9.87        68
  21 2026-04-28 06:00:00        few clouds  10.47     10.47     10.47        82
  22 2026-04-28 09:00:00  scattered clouds  12.82     12.82     12.82        76
  23 2026-04-28 12:00:00         clear sky  13.38     13.38     13.38        75
  24 2026-04-28 15:00:00         clear sky  13.21     13.21     13.21        74
  25 2026-04-28 18:00:00         clear sky  12.03     12.03     12.03        80
  26 2026-04-28 21:00:00         clear sky  10.77     10.77     10.77        81
  27 2026-04-29 00:00:00         clear sky   9.41      9.41      9.41        79
  28 2026-04-29 03:00:00         clear sky   8.11      8.11      8.11        82
  29 2026-04-29 06:00:00         clear sky   8.61      8.61      8.61        72
  30 2026-04-29 09:00:00         clear sky  12.31     12.31     12.31        60
  31 2026-04-29 12:00:00         clear sky  15.01     15.01     15.01        54
  32 2026-04-29 15:00:00         clear sky  15.88     15.88     15.88        56
  33 2026-04-29 18:00:00         clear sky  14.76     14.76     14.76        64
  34 2026-04-29 21:00:00         clear sky  11.96     11.96     11.96        70
  35 2026-04-30 00:00:00         clear sky  11.12     11.12     11.12        65
  36 2026-04-30 03:00:00         clear sky   9.92      9.92      9.92        65
  37 2026-04-30 06:00:00         clear sky   9.79      9.79      9.79        64
  38 2026-04-30 09:00:00         clear sky  14.07     14.07     14.07        56
  39 2026-04-30 12:00:00         clear sky  16.81     16.81     16.81        51

      rain_probability  cloudiness  wind_speed
  0                  0          33        4.54
  1                  0          37        4.89
  2                  0           7        3.64
  3                  0           6        2.61
  4                  0          95        2.87
  5                  0          98        2.92
  6                  0          96        2.30
  7                  0          97        2.21
  8                  0         100        2.35
  9                  0         100        4.34
  10                 0         100        4.44
  11                 0         100        2.73
  12                 0         100        1.68
  13                 0         100        2.37
  14                 0         100        3.39
  15                 0          80        5.72
  16                 0          16        6.74
  17                 0          56        4.55
  18                 0           7        3.96
  19                 0           9        3.82

**3.3 Weather preferences**

For most people, a comfortable weather for holidays is : 
- hot but not too hot (around 25°C), 
- with low humidity, wind and clouds. 
- low rain probability

We are going to create a scoring functions with these parameters to determine the weather score of a given city. Then will be able to compare cities and select the best ones.

In [21]:
 
def score_city_weather(weather_df, ideal_temp=25):
    """Score a city's weather based on 7-day forecast."""
    
    # Aggregate by day
    daily = weather_df.groupby(weather_df['dt_txt'].dt.date).agg({
        'temp': 'mean',
        'temp_min': 'min',
        'temp_max': 'max',
        'humidity': 'mean',
        'rain_probability': 'mean'
    })
    
    # Calculate component scores [0, 1]
    temp_score = (1 - abs(daily['temp'] - ideal_temp) / 10).clip(0, 1)
    humidity_score = 1 - (daily['humidity'] / 100)
    rain_score = 1 - daily['rain_probability']
    stability_score = (1 - (daily['temp_max'] - daily['temp_min']) / 10).clip(0, 1)
    
    # Weighted final score
    daily_score = (
        0.4 * temp_score +
        0.2 * humidity_score +
        0.3 * rain_score +
        0.1 * stability_score
    )
    
    # City score: mean minus std (penalize variability)
    city_score = daily_score.mean() - daily_score.std()
    
    return {
        'avg_temp': daily['temp'].mean(),
        'avg_humidity': daily['humidity'].mean(),
        'rain_prob': daily['rain_probability'].mean() * 100,
        'temp_stability': daily['temp'].std(),
        'score': city_score
    }
 
 
def calculate_weather_scores(weather_results):
    """Calculate scores for all cities."""
    
    scores = []
    
    for city, (weather_df, success) in weather_results.items():
        if not success or weather_df.empty:
            continue
        
        stats = score_city_weather(weather_df)
        scores.append({
            'City': city,
            'Weather_Score': round(stats['score'], 3),
            'Avg_Temp': round(stats['avg_temp'], 1),
            'Avg_Humidity': round(stats['avg_humidity'], 1),
            'Rain_Probability': round(stats['rain_prob'], 1),
            'Temp_Stability': round(stats['temp_stability'], 2)
        })
    
    df = pd.DataFrame(scores).sort_values('Weather_Score', ascending=False).reset_index(drop=True)
    return df

**3.4. Weather scoring for all cities**

In [22]:
weather_score_all_df = calculate_weather_scores(weather_all_cities_dict)
weather_score_all_df

,City,Weather_Score,Avg_Temp,Avg_Humidity,Rain_Probability,Temp_Stability
0,Saintes Maries de la mer,0.435,16.8,72.8,2.8,0.76
1,Nimes,0.434,17.8,60.7,2.1,1.36
2,Carcassonne,0.425,18.2,72.3,7.6,1.42
3,Marseille,0.417,17.3,67.1,3.1,1.41
4,Toulouse,0.412,17.7,68.7,4.1,1.44
5,Aix en Provence,0.401,17.2,57.8,5.8,1.36
6,Avignon,0.396,17.5,60.5,1.9,1.66
7,Le Havre,0.396,12.8,66.5,0.0,1.29
8,Cassis,0.395,16.1,69.6,1.4,1.32
9,St Malo,0.389,4.8,49.1,0.0,2.11
10,Montauban,0.385,17.0,72.4,3.0,1.36
11,Aigues Mortes,0.383,16.8,72.3,8.3,0.67
12,Paris,0.377,15.4,44.8,0.4,2.04
13,Lille,0.376,12.3,57.0,0.8,0.99
14,Uzes,0.375,17.0,61.5,2.4,1.94
15,Bormes les Mimosas,0.375,15.1,75.8,0.4,0.67
16,Chateau du Haut Koenigsbourg,0.374,10.3,58.5,0.0,2.48
17,Strasbourg,0.365,12.9,55.1,0.0,2.35
18,Eguisheim,0.363,12.8,57.4,0.0,2.41
19,Colmar,0.359,13.1,57.7,0.0,2.44
20,Bayeux,0.357,11.7,76.4,0.0,1.50
21,Besancon,0.355,13.3,63.9,0.0,1.68
22,Mont Saint Michel,0.351,13.3,69.3,0.0,1.58
23,Amiens,0.351,11.8,64.2,2.1,1.35
24,Grenoble,0.346,16.2,67.4,1.4,2.73
25,Dijon,0.345,12.9,65.2,0.0,2.30
26,Rouen,0.344,12.6,66.5,0.4,1.94
27,Biarritz,0.338,15.3,80.9,7.2,0.38
28,La Rochelle,0.334,15.0,71.6,10.9,1.24
29,Lyon,0.328,15.7,61.5,3.4,2.75
30,Bayonne,0.319,15.3,80.8,7.8,0.44
31,Collioure,0.301,18.3,73.6,27.6,1.82
32,Annecy,0.298,14.0,67.5,4.3,3.14
33,Gorges du Verdon,0.257,12.4,69.6,13.5,2.08
34,Ariege,0.206,12.8,80.1,30.8,0.68

**3.5. Export of the data**

In [23]:
weather_score_all_df.to_csv("DATA/bookinghotels/weather_best_destinations.csv", index=False)

Top five destinations according to our weather scoring :

In [24]:
top_five_destinations_df = weather_score_all_df.head(5).copy()
top_five_cities_names = weather_score_all_df.head(5)["City"].tolist()

In [25]:
print("The best cities according to the actual weather forecast are :\n")
for name, i in zip(top_five_cities_names,range(1,6)) : 
    print(f"  - N°{i} : {name}")

The best cities according to the actual weather forecast are :

  - N°1 : Saintes Maries de la mer
  - N°2 : Nimes
  - N°3 : Carcassonne
  - N°4 : Marseille
  - N°5 : Toulouse

In [26]:
top_five_destinations_df.to_csv("DATA/bookinghotels/top_five_destinations_csv.csv", index=True)

## **II. Identification of the 20 best hotels in the top-5 destinations**

Now that we have defined our top-5 list of destinations, let's check the 20 bests hotels per city using webscrapping techniques on the Booking.com website

### **1. Create a webscrapping function**

As Booking.com actively blocks scraping, we are using Selenium here to gather information for each hotel with : 
- its name,
- the url to its booking.com page,
- Its coordinates: latitude and longitude,
- Its score according to the website users,
- A text description of the hotel.

In [27]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
from datetime import datetime, timedelta, date

In [28]:
def scrape_hotels(city, check_in, check_out, num_hotels=20):
    """Scrape hotels for one city from Booking.com."""
    
    options = Options()
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
    options.add_argument("--no-sandbox")
    
    driver = webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=options
    )
    
    hotels = []
    
    try:
        url = f"https://www.booking.com/searchresults.fr.html?ss={city}&checkin={check_in}&checkout={check_out}&nrpersons=2"
        driver.get(url)
        
        # Wait and scroll
        time.sleep(3)
        driver.execute_script("window.scrollBy(0, window.innerHeight);")
        time.sleep(2)
        
        # Extract hotels
        hotel_elements = driver.find_elements(By.CSS_SELECTOR, "div[data-testid='property-card']")
        
        for elem in hotel_elements[:num_hotels]:
            try:
                # Name
                name = elem.find_element(By.CSS_SELECTOR, "div[data-testid='title']").text
                
                # URL
                link = elem.find_element(By.CSS_SELECTOR, "a[href*='hotel']")
                url_hotel = link.get_attribute("href")
                if not url_hotel.startswith("http"):
                    url_hotel = "https://www.booking.com" + url_hotel
                
                # Rating
                rating = None
                try:
                    import re
                    rating_text = elem.text
                    match = re.search(r'(\d+[.,]\d)', rating_text)
                    if match:
                        rating = float(match.group(1).replace(',', '.'))
                except:
                    pass
                
                hotels.append({
                    'name': name,
                    'url': url_hotel,
                    'rating': rating,
                    'city': city
                })
            except:
                continue
    
    except Exception as e:
        print(f"Error scraping {city}: {str(e)}")
    
    finally:
        driver.quit()
    
    return hotels

### **2. Get hotels information**

In [29]:
def scrape_all_hotels(cities, check_in=None, check_out=None, num_hotels=20):
    """Scrape hotels for all cities."""
    
    if check_in is None:
        check_in = date.today()
        
    if check_out is None:
        check_out = check_in + timedelta(days=7)

    print(check_in, check_out)
    all_hotels = []
    
    for city in cities:
        hotels = scrape_hotels(city, check_in, check_out, num_hotels)
        all_hotels.extend(hotels)
    
    if not all_hotels:
        print("No hotels scraped!")
        return pd.DataFrame()
    
    df = pd.DataFrame(all_hotels)
    df = df.sort_values(['city', 'rating'], ascending=[True, False]).reset_index(drop=True)
    
    return df

In [30]:
cities = top_five_cities_names
assert isinstance(cities, list) and all(isinstance(c, str) for c in cities), \
    f"top_five_cities_names must be a string, received : {cities}"
print(f"Villes à scraper ({len(cities)}) : {cities}")

Villes à scraper (5) : ['Saintes Maries de la mer', 'Nimes', 'Carcassonne', 'Marseille', 'Toulouse']

In [31]:
hotels_df = scrape_all_hotels(cities)

2026-04-25 2026-05-02

In [32]:
hotels_df.head()

,name,url,rating,city
0,Le Petit Capoine 2- T2 Plein Centre de Carcass...,https://www.booking.com/hotel/fr/le-petit-capo...,9.8,Carcassonne
1,Le Clos Saint Michel,https://www.booking.com/hotel/fr/le-clos-saint...,9.2,Carcassonne
2,L'Impasse d'Adam Free Parking,https://www.booking.com/hotel/fr/impasse-d-ada...,9.1,Carcassonne
3,Le Casimir - Appartement de standing 90m2 - Ca...,https://www.booking.com/hotel/fr/le-casimir-h-...,8.8,Carcassonne
4,L'Eva-Ambre - 2 Chambres - Parking & Clim,https://www.booking.com/hotel/fr/eva-ambre-2-c...,8.7,Carcassonne

In [33]:
# Save to CSV
hotels_df.to_csv("DATA/bookinghotels/all_cities_hotels.csv", index=False)
hotels_df.head()

,name,url,rating,city
0,Le Petit Capoine 2- T2 Plein Centre de Carcass...,https://www.booking.com/hotel/fr/le-petit-capo...,9.8,Carcassonne
1,Le Clos Saint Michel,https://www.booking.com/hotel/fr/le-clos-saint...,9.2,Carcassonne
2,L'Impasse d'Adam Free Parking,https://www.booking.com/hotel/fr/impasse-d-ada...,9.1,Carcassonne
3,Le Casimir - Appartement de standing 90m2 - Ca...,https://www.booking.com/hotel/fr/le-casimir-h-...,8.8,Carcassonne
4,L'Eva-Ambre - 2 Chambres - Parking & Clim,https://www.booking.com/hotel/fr/eva-ambre-2-c...,8.7,Carcassonne

### **3. Visualizations**

**3.1. Top destinations map**

In [34]:
import plotly.express as px

def plot_top_destinations(df):
    """Interactive map with modern Mapbox-style background."""

    top5 = df.head(5)

    fig = px.scatter_mapbox(
        top5,
        lat="Latitude",
        lon="Longitude",
        text="City",
        zoom=4.5,
        center={"lat": 46.6, "lon": 2.5},  # France
        height=600
    )

    fig.update_traces(
        marker=dict(size=10, color="red"),
        hovertemplate="<b>%{text}</b><extra></extra>"
    )

    fig.update_layout(
        mapbox_style="carto-positron",  
        margin={"r":0,"t":40,"l":0,"b":0},
        title="<b>Top 5 Best Destinations in France</b>"
    )

    return fig

In [35]:
coordinates_35_cities = pd.read_csv("DATA/bookinghotels/coordinates_35_cities_csv.csv")

In [38]:
selected_cities = ['Saintes Maries de la mer',
                    'Nimes', 
                    'Carcassonne', 
                    'Marseille', 
                    'Toulouse']

# filtrer les 5 villes
top_cities_coordinates = coordinates_35_cities[coordinates_35_cities["City"].isin(selected_cities)]

In [39]:
top_cities_coordinates

                        City   Latitude  Longitude
20                 Marseille  43.296174   5.369953
24                     Nimes  43.837425   4.360069
26  Saintes Maries de la mer  43.451592   4.427720
28               Carcassonne  43.213036   2.349107
30                  Toulouse  43.604464   1.444243

In [40]:
plot_top_destinations(top_cities_coordinates)

**3.2. Top hotels map**

In [41]:
hotels_df.head()

,name,url,rating,city
0,Le Petit Capoine 2- T2 Plein Centre de Carcass...,https://www.booking.com/hotel/fr/le-petit-capo...,9.8,Carcassonne
1,Le Clos Saint Michel,https://www.booking.com/hotel/fr/le-clos-saint...,9.2,Carcassonne
2,L'Impasse d'Adam Free Parking,https://www.booking.com/hotel/fr/impasse-d-ada...,9.1,Carcassonne
3,Le Casimir - Appartement de standing 90m2 - Ca...,https://www.booking.com/hotel/fr/le-casimir-h-...,8.8,Carcassonne
4,L'Eva-Ambre - 2 Chambres - Parking & Clim,https://www.booking.com/hotel/fr/eva-ambre-2-c...,8.7,Carcassonne

As we cannot get the exact adress of the hotels from booking.com we will find them with the API Nominatum :

In [42]:
def geocode_hotels(hotels_df):
    url_base = "https://nominatim.openstreetmap.org/search"
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/118.0"}
    latitudes, longitudes, addresses = [], [], []

    for _, row in hotels_df.iterrows():
        found = False
        queries = [
            f"{row['name']}, {row['city']}, France",
            f"{row['city']}, France"
        ]
        for query in queries:
            params = {"q": query, "format": "json", "addressdetails": "1", "limit": "1"}
            try:
                response = requests.get(url=url_base, headers=headers, params=params, timeout=10)
                time.sleep(1)  # Respect rate-limit 
                if response.status_code == 200 and response.json():
                    result = response.json()[0]
                    latitudes.append(float(result["lat"]))
                    longitudes.append(float(result["lon"]))
                    addresses.append(result.get("display_name", ""))
                    found = True
                    break
            except Exception:
                pass
        if not found:
            latitudes.append(None)
            longitudes.append(None)
            addresses.append("")

    enriched = hotels_df.copy()
    enriched["latitude"]  = latitudes
    enriched["longitude"] = longitudes
    enriched["address"]   = addresses
    return enriched

hotels_df = geocode_hotels(hotels_df)
hotels_df.to_csv("DATA/bookinghotels/all_cities_hotels_geocoded.csv", index=False)
print(f"Geocoded {hotels_df['latitude'].notna().sum()} / {len(hotels_df)} hotels")
hotels_df.head()

Geocoded 100 / 100 hotels

,name,url,rating,city,latitude,longitude,address
0,Le Petit Capoine 2- T2 Plein Centre de Carcass...,https://www.booking.com/hotel/fr/le-petit-capo...,9.8,Carcassonne,43.213036,2.349107,"Carcassonne, Aude, Occitanie, France métropoli..."
1,Le Clos Saint Michel,https://www.booking.com/hotel/fr/le-clos-saint...,9.2,Carcassonne,43.213036,2.349107,"Carcassonne, Aude, Occitanie, France métropoli..."
2,L'Impasse d'Adam Free Parking,https://www.booking.com/hotel/fr/impasse-d-ada...,9.1,Carcassonne,43.213036,2.349107,"Carcassonne, Aude, Occitanie, France métropoli..."
3,Le Casimir - Appartement de standing 90m2 - Ca...,https://www.booking.com/hotel/fr/le-casimir-h-...,8.8,Carcassonne,43.213036,2.349107,"Carcassonne, Aude, Occitanie, France métropoli..."
4,L'Eva-Ambre - 2 Chambres - Parking & Clim,https://www.booking.com/hotel/fr/eva-ambre-2-c...,8.7,Carcassonne,43.213036,2.349107,"Carcassonne, Aude, Occitanie, France métropoli..."

In [46]:
def plot_top_hotels(hotels_df, city=None):
    hotels_with_coords = hotels_df.dropna(subset=["latitude", "longitude"])
    if hotels_with_coords.empty:
        print("No hotels with coordinates. Run geocode_hotels() first.")
        return None
    if city:
        plot_df = (hotels_with_coords[hotels_with_coords["city"] == city]
                   .dropna(subset=["rating"])          
                   .nlargest(20, "rating"))
        title = f"<b>Top 20 Hotels — {city}</b>"
        zoom, center = 12, {"lat": plot_df["latitude"].mean(), "lon": plot_df["longitude"].mean()}
    else:
        plot_df = (hotels_with_coords
                   .dropna(subset=["rating"])         
                   .sort_values("rating", ascending=False)
                   .groupby("city").head(5).reset_index(drop=True))
        title = "<b>Top 5 Hotels per Destination</b>"
        zoom, center = 5, {"lat": 43.5, "lon": 4.0}

    if plot_df.empty:
        print(f"No hotels with valid rating{' in ' + city if city else ''}.")
        return None

    fig = px.scatter_mapbox(plot_df, lat="latitude", lon="longitude", color="city",
        size="rating", size_max=15, hover_name="name",
        hover_data={"rating": True, "city": True, "address": True,
                    "latitude": False, "longitude": False},
        zoom=zoom, center=center, height=600, title=title)
    fig.update_layout(mapbox_style="carto-positron", margin={"r":0,"t":40,"l":0,"b":0})
    return fig

In [47]:
fig_hotels_overview = plot_top_hotels(hotels_df)
if fig_hotels_overview:
    fig_hotels_overview.show()
for city_name in top_five_cities_names:
    fig_city = plot_top_hotels(hotels_df, city=city_name)
    if fig_city:
        fig_city.show()

### **4. Save elements to S3** ###

In [ ]:
! pip install boto3

In [55]:
import boto3
import logging
from dotenv import load_dotenv
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

In [56]:
load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Création du client S3 avec les credentials du .env
s3_client = boto3.client(
    's3',
    aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
    region_name=os.getenv("AWS_DEFAULT_REGION")
)

In [57]:
def upload_to_s3(dataframe, filename, bucket_name):
    try:
        csv_buffer = dataframe.to_csv(index=False).encode('utf-8')
        s3_client.put_object(Bucket=bucket_name, Key=filename, Body=csv_buffer)
        logger.info(f"✓ Uploaded {filename} to s3://{bucket_name}/")
    except Exception as e:
        logger.error(f"Failed to upload {filename}: {str(e)}")

def save_figure_to_s3(figure, filename, bucket_name):
    try:
        html_string = figure.to_html()
        s3_client.put_object(
            Bucket=bucket_name,
            Key=filename,
            Body=html_string.encode('utf-8'),
            ContentType='text/html'
        )
        logger.info(f"✓ Uploaded {filename} to s3://{bucket_name}/")
    except Exception as e:
        logger.error(f"Failed to upload {filename}: {str(e)}")

In [59]:
BUCKET = "kayak-project-mt"
PREFIX = "weather and hotels/"

upload_to_s3(df_coord_35_cities,       PREFIX + "data/coordinates_35_cities.csv",     BUCKET)
upload_to_s3(weather_score_all_df,     PREFIX + "data/weather_best_destinations.csv",  BUCKET)
upload_to_s3(top_five_destinations_df, PREFIX + "data/top_five_destinations.csv",      BUCKET)
upload_to_s3(hotels_df,                PREFIX + "data/all_cities_hotels_geocoded.csv", BUCKET)

fig_destinations = plot_top_destinations(top_cities_coordinates)
save_figure_to_s3(fig_destinations,    PREFIX + "maps/top_destinations_map.html",      BUCKET)
save_figure_to_s3(fig_hotels_overview, PREFIX + "maps/top_hotels_overview.html",       BUCKET)
for city_name in top_five_cities_names:
    fig_city = plot_top_hotels(hotels_df, city=city_name)
    if fig_city:
        city_slug = city_name.lower().replace(" ", "_")
        save_figure_to_s3(fig_city, PREFIX + f"maps/hotels_{city_slug}.html", BUCKET)

INFO:__main__:✓ Uploaded weather and hotels/data/coordinates_35_cities.csv to s3://kayak-project-mt/
INFO:__main__:✓ Uploaded weather and hotels/data/weather_best_destinations.csv to s3://kayak-project-mt/
INFO:__main__:✓ Uploaded weather and hotels/data/top_five_destinations.csv to s3://kayak-project-mt/
INFO:__main__:✓ Uploaded weather and hotels/data/all_cities_hotels_geocoded.csv to s3://kayak-project-mt/
INFO:__main__:✓ Uploaded weather and hotels/maps/top_destinations_map.html to s3://kayak-project-mt/
INFO:__main__:✓ Uploaded weather and hotels/maps/top_hotels_overview.html to s3://kayak-project-mt/
INFO:__main__:✓ Uploaded weather and hotels/maps/hotels_saintes_maries_de_la_mer.html to s3://kayak-project-mt/
INFO:__main__:✓ Uploaded weather and hotels/maps/hotels_nimes.html to s3://kayak-project-mt/
INFO:__main__:✓ Uploaded weather and hotels/maps/hotels_carcassonne.html to s3://kayak-project-mt/
INFO:__main__:✓ Uploaded weather and hotels/maps/hotels_marseille.html to s3://kayak-project-mt/
INFO:__main__:✓ Uploaded weather and hotels/maps/hotels_toulouse.html to s3://kayak-project-mt/

## **Conclusion**

This project combined weather forecasting APIs, geolocation data, and web scraping to recommend the best holiday destinations in France for the coming week.

Based on the 7-day weather forecast scored across temperature, humidity, rainfall probability and stability, the **top 5 destinations** identified are:

1. **Saintes-Maries-de-la-Mer**
2. **Nîmes**
3. **Carcassonne**
4. **Marseille**
5. **Toulouse**

All five cities are located in the south of France, which is consistent with the expected sunny and dry weather conditions typical of the Mediterranean and Occitanie regions in spring.

For each of these destinations, the top-rated hotels were scraped from Booking.com and geocoded using the Nominatim API, then visualised on interactive maps.

### *Limitations*

- **Booking.com actively blocks automated scraping**, which means the number of hotels retrieved per city is limited and may not be representative of all available options. Some hotels may be missing from the maps entirely due to failed scraping attempts or bot-detection mechanisms.
- The weather scoring model is based on a **fixed set of preferences** (ideal temperature ~25°C, low humidity and rain probability). Results would differ for users with different comfort thresholds.
- The Nominatim API has a **rate limit of 1 request per second**, which slows down geocoding and can occasionally return approximate coordinates — especially for hotel names that are not well-referenced in OpenStreetMap.
- The analysis is a **snapshot in time**: re-running the notebook a few days later would likely produce different top destinations as the weather forecast updates.